In [1]:
import matplotlib
matplotlib.use('Qt5Agg')  # Important for VSCode interactivity

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import PolygonSelector
from matplotlib.path import Path
from matplotlib.colors import LinearSegmentedColormap
import scanpy as sc

import numpy as np
import os
import plotly.io as pio
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import scipy.sparse as sp
from anndata import AnnData

In [2]:
class PolygonAnnotator:
    def __init__(self, image, cmap='hot'):
        self.image = image
        self.coords = None
        self.done = False

        self.fig, self.ax = plt.subplots()
        self.ax.imshow(image, cmap=cmap)
        self.ax.set_title("Click to draw polygon. Double-click to finish.")

        self.selector = PolygonSelector(
            self.ax,
            self.onselect,
            useblit=True,
            props=dict(color='cyan', linewidth=2),
            handle_props=dict(marker='o', markersize=5, mec='cyan', mfc='cyan')
        )

        self.fig.canvas.mpl_connect('close_event', self._on_close)
        plt.show(block=True)  # Blocks until the window is closed

    def _on_close(self, event):
        self.done = True

    def onselect(self, verts):
        self.coords = verts
        print(f"Polygon drawn with {len(verts)} points.")
        plt.close(self.fig)  # Automatically close the window

    def get_mask(self):
        if not self.coords:
            print("No polygon was drawn.")
            return None
        ny, nx = self.image.shape
        y, x = np.mgrid[:ny, :nx]
        points = np.vstack((x.flatten(), y.flatten())).T
        path = Path(self.coords)
        return path.contains_points(points).reshape((ny, nx))

In [3]:
def get_mz_heatmap_image(adata, target_mz, tol=0.1):
    mz_axis = adata.var_names.astype(float).values
    mz_diff = np.abs(mz_axis - target_mz)
    if np.min(mz_diff) > tol:
        raise ValueError(f"No m/z found within ±{tol} of {target_mz}")
    mz_index = np.argmin(mz_diff)
    matched_mz = mz_axis[mz_index]

    intensities = adata.X[:, mz_index].toarray().flatten() if hasattr(adata.X, "toarray") else adata.X[:, mz_index]
    x = adata.obs["x"].values.astype(int)
    y = adata.obs["y"].values.astype(int)

    width = x.max() + 1
    height = y.max() + 1
    image = np.zeros((height, width))
    image[y, x] = intensities

    return image, matched_mz

In [4]:
# Load and visualize the m/z heatmap from AnnData
input_file = "/Users/amin/Desktop/PhD_Thesis/Code/IMZML Tools/a_peaks_0.00001_top1000_9w_3p_5points.h5ad"
adata = sc.read_h5ad(input_file)
print(f"Loaded AnnData from: {input_file}")

Loaded AnnData from: /Users/amin/Desktop/PhD_Thesis/Code/IMZML Tools/a_peaks_0.00001_top1000_9w_3p_5points.h5ad

In [5]:
def sort_adata_by_mz(adata, mz_column="mzs"):
    def to_float_with_warning(index, label="var_names"):
        mzs = pd.to_numeric(index, errors="coerce")
        n_nans = mzs.isna().sum()
        if n_nans > 0:
            print(f"⚠️ Warning: {n_nans} entries in {label} could not be converted to float and were set to NaN.")
        return mzs
    adata.var[mz_column] = to_float_with_warning(adata.var_names)
    adata = adata[:, adata.var[mz_column].sort_values().index]
    return adata

In [6]:
adata = sort_adata_by_mz(adata, mz_column="mzs")
adata.var

                 mzs
136.0150    136.0150
136.0608    136.0608
137.0251    137.0251
138.0287    138.0287
139.0359    139.0359
...              ...
1520.1588  1520.1588
1521.1633  1521.1633
1522.1682  1522.1682
1542.1475  1542.1475
1544.1542  1544.1542

[1000 rows x 1 columns]

In [7]:
# ---- Run ----

target_mz = 788.5
image, matched_mz = get_mz_heatmap_image(adata, target_mz)
print(f"Target m/z: {target_mz} → Matched m/z: {matched_mz}")

'''custom_cmap = LinearSegmentedColormap.from_list("custom_scale", [
    (0.0, "#000000"),  # black
    (0.10, "#000080"),  # navy
    (0.15, "#0000FF"),  # blue
    (0.30, "#8000FF"),  # purple-ish
    (0.45, "#FF0000"),  # red
    (0.60, "#FF8000"),  # orange
    (0.75, "#FFFF00"),  # yellow
    (1.0, "#FFFFFF")   # white
])
'''
custom_cmap = "binary"
# Use the annotator with your image and colormap
annotator = PolygonAnnotator(image, cmap=custom_cmap)
mask = annotator.get_mask()

if mask is not None:
    masked_image = np.where(mask, image, 0)
    plt.imshow(masked_image, cmap=custom_cmap)
    plt.title(f"Masked m/z = {matched_mz:.4f}")
    plt.show()
else:
    print("No mask created.")

Target m/z: 788.5 → Matched m/z: 788.5027
Polygon drawn with 34 points.

In [8]:
# Get spatial coordinates
x = adata.obs["x"].astype(int).values
y = adata.obs["y"].astype(int).values

# Mask value at each spot
adata.obs["tissue"] = mask[y, x]  # Boolean mask (True = inside polygon)
adata.obs["tissue"] = adata.obs["tissue"].astype(int)  # 1 = inside, 0 = outside
print(adata.obs["tissue"].value_counts())

tissue
0    9454
1    7151
Name: count, dtype: int64

/var/folders/0n/w0dydx896p7b5chql0_cv6hr0000gn/T/ipykernel_21693/1596079847.py:6: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata.obs["tissue"] = mask[y, x]  # Boolean mask (True = inside polygon)

In [9]:
adata1 = adata
adata.obs["tissue"]

0        0
1        0
2        0
3        0
4        0
        ..
16600    0
16601    0
16602    0
16603    0
16604    0
Name: tissue, Length: 16605, dtype: int64

In [10]:
adata = adata1
adata

AnnData object with n_obs × n_vars = 16605 × 1000
    obs: 'x', 'y', 'TIC', 'sample', 'batch', 'age_group', 'disease_status', 'tissue'
    var: 'mzs'

In [11]:
def filter_mz_by_tissue(adata, tissue_key="tissue", tissue_val=1, non_tissue_val=0, foldchange=2.0, layer=None, normalize_tic=True):
    # 1. Extract raw data
    data = adata.layers[layer] if layer is not None else adata.X

    # 2. TIC normalization per pixel
    if normalize_tic:
        # Sum across features for each observation (axis=1)
        tic = np.asarray(data.sum(axis=1)).ravel()
        # Avoid division by zero
        tic[tic == 0] = 1.0
        # Normalize in place (if sparse, convert to array)
        data = data / tic[:, None]

    # 3. Define tissue masks
    mask_tissue = adata.obs[tissue_key] == tissue_val
    mask_non    = adata.obs[tissue_key] == non_tissue_val

    # 4. Compute mean normalized intensity per feature
    mean_tissue    = np.asarray(data[mask_tissue].mean(axis=0)).ravel()
    mean_nontissue = np.asarray(data[mask_non].mean(axis=0)).ravel()

    # 5. Identify features to remove
    to_remove = mean_tissue < foldchange * mean_nontissue

    # 6. Print removed m/z names
    mz_to_remove = adata.var_names[to_remove]
    print(f"Dropping {len(mz_to_remove)} m/z features:", mz_to_remove.values)

    # 7. Subset and return
    return adata[:, ~to_remove].copy()

In [12]:
foldchange = 3

# Filter m/z features based on tissue mask
#adata = filter_mz_by_tissue(adata, tissue_key="tissue", tissue_val=1, non_tissue_val=0, foldchange=foldchange, layer=None, normalize_tic=True)

In [13]:
adata

AnnData object with n_obs × n_vars = 16605 × 1000
    obs: 'x', 'y', 'TIC', 'sample', 'batch', 'age_group', 'disease_status', 'tissue'
    var: 'mzs'

In [14]:
adata.var_names

Index(['136.0150', '136.0608', '137.0251', '138.0287', '139.0359', '154.0255',
       '155.0350', '156.0424', '159.0070', '160.0107',
       ...
       '1249.0300', '1255.0399', '1271.0072', '1494.1565', '1495.1523',
       '1520.1588', '1521.1633', '1522.1682', '1542.1475', '1544.1542'],
      dtype='object', length=1000)

In [15]:
def plot_mz_across_sample_custom_tic(adata, target_mz, tol=0.1):
    """
    Plots the TIC-normalized intensity of a specific m/z across all pixels using spatial coordinates.

    Parameters:
    - adata: AnnData object with MSI data
    - target_mz: float, the m/z value of interest
    - tol: float, tolerance for matching m/z (default ±0.1)
    """
    # Convert var_names to float (m/z axis)
    mz_axis = adata.var_names.astype(float).values

    # Find index of the m/z closest to the target within tolerance
    mz_diff = np.abs(mz_axis - target_mz)
    if np.min(mz_diff) > tol:
        raise ValueError(f"No m/z found within ±{tol} of {target_mz}")
    mz_index = np.argmin(mz_diff)
    matched_mz = mz_axis[mz_index]

    # Extract intensities for that m/z from all pixels
    intensities = adata.X[:, mz_index].toarray().flatten() if hasattr(adata.X, "toarray") else adata.X[:, mz_index]

    # Normalize by TIC
    if "TIC" not in adata.obs.columns:
        raise KeyError("TIC not found in adata.obs. Compute TIC before using this function.")
    tic = adata.obs["TIC"].values
    norm_intensities = intensities / tic
    norm_intensities[np.isnan(norm_intensities)] = 0  # Avoid NaNs from division by 0

    # Extract spatial coordinates
    if "x" not in adata.obs.columns or "y" not in adata.obs.columns:
        raise KeyError("Spatial coordinates 'x' and 'y' not found in adata.obs")

    x = adata.obs["x"].values
    y = adata.obs["y"].values

    # Create DataFrame for plotting
    df = pd.DataFrame({"x": x, "y": y, "intensity": norm_intensities})

    # Plot as heatmap using plotly express
    fig = px.scatter(
        df,
        x="x",
        y="y",
        color="intensity",
        color_continuous_scale=[
            [0.0, "#000000"],  # black
            [0.10, "#000080"],  # navy
            [0.15, "#0000FF"],  # blue
            [0.30, "#8000FF"],  # purple-ish
            [0.45, "#FF0000"],  # red
            [0.60, "#FF8000"],  # orange
            [0.75, "#FFFF00"],  # yellow
            [1.0, "#FFFFFF"]   # white
        ],
        title=f"TIC-Normalized Intensity Map of m/z = {matched_mz:.4f}",
        labels={"intensity": "Normalized Intensity"},
        height=500
    )

    fig.update_layout(yaxis=dict(scaleanchor="x", autorange="reversed"))
    return fig

In [16]:


# Ensure the image folder exists
os.makedirs(f"images_{foldchange}", exist_ok=True)

# Compute the global spectrum
global_spectrum = adata.X.sum(axis=0).A1 if hasattr(adata.X, "A1") else np.asarray(adata.X.sum(axis=0)).flatten()

# Get indices of m/z values sorted by intensity (descending)
sorted_indices = np.argsort(global_spectrum)[::-1]

# Select indices from 10th to 20th (ranked #10 to #20)
selected_indices = sorted_indices[0:]

# Get corresponding m/z values
selected_mz = adata.var_names[selected_indices].astype(float)
"""
# Modified plotting loop
for mz in selected_mz:
    # Generate figure using your existing function
    fig = plot_mz_across_sample_custom_tic(adata, mz, tol=0.001)  # Modify function to return fig
    
    # Define filename
    filename = f"images_{foldchange}/mz_{mz:.4f}.png"
    
    # Save the figure
    pio.write_image(fig, filename)
    print(f"Saved: {filename}")

"""

'\n# Modified plotting loop\nfor mz in selected_mz:\n    # Generate figure using your existing function\n    fig = plot_mz_across_sample_custom_tic(adata, mz, tol=0.001)  # Modify function to return fig\n    \n    # Define filename\n    filename = f"images_{foldchange}/mz_{mz:.4f}.png"\n    \n    # Save the figure\n    pio.write_image(fig, filename)\n    print(f"Saved: {filename}")\n\n'

In [17]:
def mask_low_background_intensities(adata, fold_change=0.1):
    """
    Set background pixel intensities (tissue==0) to 0 if they are below fold_change * max tissue intensity per m/z.
    
    Parameters:
        adata : AnnData
            An AnnData object where .X is (n_pixels x n_mz) and .obs["tissue"] exists.
        fold_change : float
            The threshold multiplier to compare background intensity to max tissue intensity.
    """
    X = adata.X
    tissue_mask = adata.obs["tissue"] == 1
    background_mask = ~tissue_mask

    if sp.issparse(X):
        X = X.tocsr()

    # Compute max intensity of each m/z in tissue pixels
    max_tissue_intensity = X[tissue_mask.values].max(axis=0).A1 if sp.issparse(X) else X[tissue_mask.values].max(axis=0)

    # Define threshold per m/z
    thresholds = fold_change * max_tissue_intensity

    # Modify background pixels
    bg_indices = np.where(background_mask)[0]

    for i in bg_indices:
        row = X[i]
        if sp.issparse(X):
            row = row.tocoo()
            mask = row.data <= thresholds[row.col]
            row.data[mask] = 0
            X[i] = sp.csr_matrix((row.data, (np.zeros_like(row.col), row.col)), shape=(1, X.shape[1]))
        else:
            mask = row <= thresholds
            row[mask] = 0
            X[i] = row

    adata.X = X
    return adata

In [18]:
#adata = mask_low_background_intensities(adata, fold_change=0.01)

In [19]:
def export_pixel_areas_to_csv_with_centroid(
    adata: AnnData,
    pixel_area: float = 100.0,
    output_csv: str = "pixel_area_summary.csv",
    x_key: str = "x",
    y_key: str = "y",
):
    """
    Calculates and exports per-m/z area, intensity sum, and centroid info to a CSV.

    Parameters:
        adata : AnnData
            AnnData object with .X, .obs["tissue"], .obs["x"], .obs["y"], and .var["mzs"] or .var_names
        pixel_area : float
            Area of a single pixel (e.g., in μm²)
        output_csv : str
            Output CSV filename
        x_key : str
            Key in adata.obs for x coordinates
        y_key : str
            Key in adata.obs for y coordinates
    """
    X = adata.X
    if sp.issparse(X):
        X = X.tocsr()

    if "mzs" in adata.var.columns:
        mz_values = adata.var["mzs"].values
    else:
        mz_values = pd.to_numeric(adata.var_names, errors="coerce")
        print("Warning: 'mzs' not found in var. Using var_names instead.")

    # Masks
    tissue_mask = adata.obs["tissue"] == 1
    background_mask = ~tissue_mask

    x_coords = adata.obs[x_key].values
    y_coords = adata.obs[y_key].values

    # Initialize lists
    on_tissue_area = []
    non_tissue_area = []
    on_tissue_sum = []
    non_tissue_sum = []
    on_tissue_centroid_x = []
    on_tissue_centroid_y = []
    non_tissue_centroid_x = []
    non_tissue_centroid_y = []

    for mz_idx in range(X.shape[1]):
        intensities = X[:, mz_idx].toarray().flatten() if sp.issparse(X) else X[:, mz_idx]

        # Tissue and background
        tissue_values = intensities[tissue_mask.values]
        bg_values = intensities[background_mask.values]

        # Area
        on_tissue_area.append(np.sum(tissue_values > 0) * pixel_area)
        non_tissue_area.append(np.sum(bg_values > 0) * pixel_area)

        # Sum
        on_tissue_sum.append(np.sum(tissue_values))
        non_tissue_sum.append(np.sum(bg_values))

        # Centroid on tissue
        tx = x_coords[tissue_mask.values]
        ty = y_coords[tissue_mask.values]
        weight = tissue_values
        total = np.sum(weight)
        if total > 0:
            on_tissue_centroid_x.append(np.sum(tx * weight) / total)
            on_tissue_centroid_y.append(np.sum(ty * weight) / total)
        else:
            on_tissue_centroid_x.append(np.nan)
            on_tissue_centroid_y.append(np.nan)

        # Centroid on background
        bx = x_coords[background_mask.values]
        by = y_coords[background_mask.values]
        weight = bg_values
        total = np.sum(weight)
        if total > 0:
            non_tissue_centroid_x.append(np.sum(bx * weight) / total)
            non_tissue_centroid_y.append(np.sum(by * weight) / total)
        else:
            non_tissue_centroid_x.append(np.nan)
            non_tissue_centroid_y.append(np.nan)

    # DataFrame
    df = pd.DataFrame({
        "m/z": mz_values,
        "on_tissue_area": on_tissue_area,
        "non_tissue_area": non_tissue_area,
        "on_tissue_sum": on_tissue_sum,
        "non_tissue_sum": non_tissue_sum,
        "on_tissue_centroid_x": on_tissue_centroid_x,
        "on_tissue_centroid_y": on_tissue_centroid_y,
        "non_tissue_centroid_x": non_tissue_centroid_x,
        "non_tissue_centroid_y": non_tissue_centroid_y,
    })

    df.to_csv(output_csv, index=False)
    print(f"Saved to {output_csv}")
    return df

In [20]:
df = export_pixel_areas_to_csv_with_centroid(
    adata,
    pixel_area = 1.0,
    output_csv = "pixel_area_summary.csv",
    x_key = "x",
    y_key = "y",
)

Saved to pixel_area_summary.csv

In [21]:
df

,m/z,on_tissue_area,non_tissue_area,on_tissue_sum,non_tissue_sum,on_tissue_centroid_x,on_tissue_centroid_y,non_tissue_centroid_x,non_tissue_centroid_y
0,136.0150,6199.0,9440.0,507975.0,6863816.0,60.242973,50.807022,70.354641,75.642289
1,136.0608,7144.0,8590.0,2220296.0,1514359.0,61.953485,51.076435,66.858048,69.307963
2,137.0251,7151.0,9454.0,22357263.0,405797380.0,60.497221,52.789303,70.297145,85.396564
3,138.0287,7122.0,9454.0,2018837.0,31881184.0,60.681929,52.381017,70.173918,82.941998
4,139.0359,6636.0,9447.0,610775.0,6889345.0,61.628978,51.347067,70.584489,80.767940
...,...,...,...,...,...,...,...,...,...
995,1520.1588,7115.0,5406.0,688890.0,199117.0,62.044035,53.981562,73.849501,59.356514
996,1521.1633,7096.0,5300.0,613397.0,178975.0,62.111782,54.245192,73.823942,60.395776
997,1522.1682,7114.0,5395.0,663447.0,195938.0,62.082337,54.573931,72.907665,58.972226
998,1542.1475,7101.0,5290.0,543954.0,150146.0,61.943859,53.265522,71.585663,56.259268
999,1544.1542,7107.0,5123.0,559931.0,145166.0,62.355528,52.804254,72.356082,57.239174

In [22]:
import matplotlib.pyplot as plt
from skimage import measure

# Get contours at a constant value of 0.5 (between 0 and 1 in binary masks)
contours = measure.find_contours(mask, level=0.5)

# Plot the image with lower opacity and overlay the contour lines
plt.imshow(image, cmap='gray', alpha=0.3)  # Faded background
for contour in contours:
    plt.plot(contour[:, 1], contour[:, 0], linewidth=2, color='red')  # (x, y) = (col, row)

plt.axis('off')
plt.title('Polygon Margin Lines')
plt.show()

In [23]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from skimage import measure

def plot_mz_centroids_with_margin_and_mask_contours(
    df,
    image,
    mask,
    cmap_on_tissue="viridis",
    cmap_non_tissue="plasma",
    square_size=100,
    circle_size=50,
    figsize=(10, 8),
    show_margin=True,
    show_mask_contours=True,
    image_alpha=0.3,
    margin_linewidth=1.5,
    contour_color="red"
):
    """
    Plot centroid heatmap for each m/z using on-tissue squares and non-tissue circles.
    Optionally overlay the original image (faded) and polygon margin contours from mask.
    """
    required_cols = [
        "on_tissue_centroid_x", "on_tissue_centroid_y", "on_tissue_sum",
        "non_tissue_centroid_x", "non_tissue_centroid_y", "non_tissue_sum"
    ]
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    norm_on_tissue = plt.Normalize(vmin=df["on_tissue_sum"].min(), vmax=df["on_tissue_sum"].max())
    norm_non_tissue = plt.Normalize(vmin=df["non_tissue_sum"].min(), vmax=df["non_tissue_sum"].max())

    cmap_on_tissue_obj = plt.colormaps[cmap_on_tissue]
    cmap_non_tissue_obj = plt.colormaps[cmap_non_tissue]

    fig, ax = plt.subplots(figsize=figsize)

    # Show background image with alpha
    ax.imshow(image, cmap='gray', alpha=image_alpha)

    # Plot centroids
    for _, row in df.iterrows():
        if not np.isnan(row["on_tissue_centroid_x"]) and not np.isnan(row["on_tissue_centroid_y"]):
            color = cmap_on_tissue_obj(norm_on_tissue(row["on_tissue_sum"]))
            square = patches.Rectangle(
                (row["on_tissue_centroid_x"] - square_size / 2, row["on_tissue_centroid_y"] - square_size / 2),
                square_size, square_size,
                linewidth=0.5, edgecolor="black", facecolor=color, alpha=0.8
            )
            ax.add_patch(square)

        if not np.isnan(row["non_tissue_centroid_x"]) and not np.isnan(row["non_tissue_centroid_y"]):
            color = cmap_non_tissue_obj(norm_non_tissue(row["non_tissue_sum"]))
            circle = patches.Circle(
                (row["non_tissue_centroid_x"], row["non_tissue_centroid_y"]),
                radius=circle_size / 2,
                linewidth=0.5, edgecolor="black", facecolor=color, alpha=0.8
            )
            ax.add_patch(circle)

    # Plot margin lines from mask
    if show_mask_contours and mask is not None:
        contours = measure.find_contours(mask, level=0.5)
        for contour in contours:
            ax.plot(contour[:, 1], contour[:, 0], linewidth=margin_linewidth, color=contour_color)

    # Optional dashed margin lines based on centroid averages
    if show_margin:
        tissue_centroids = df[["on_tissue_centroid_x", "on_tissue_centroid_y"]].dropna()
        non_tissue_centroids = df[["non_tissue_centroid_x", "non_tissue_centroid_y"]].dropna()

        if not tissue_centroids.empty:
            avg_tissue_x = tissue_centroids["on_tissue_centroid_x"].mean()
            avg_tissue_y = tissue_centroids["on_tissue_centroid_y"].mean()
            ax.plot([avg_tissue_x - 100, avg_tissue_x + 100],
                    [avg_tissue_y - 100, avg_tissue_y + 100],
                    color="black", linewidth=margin_linewidth, linestyle="--")

        if not non_tissue_centroids.empty:
            avg_non_tissue_x = non_tissue_centroids["non_tissue_centroid_x"].mean()
            avg_non_tissue_y = non_tissue_centroids["non_tissue_centroid_y"].mean()
            ax.plot([avg_non_tissue_x - 100, avg_non_tissue_x + 100],
                    [avg_non_tissue_y - 100, avg_non_tissue_y + 100],
                    color="red", linewidth=margin_linewidth, linestyle="--")

    # Colorbars
    sm_on_tissue = plt.cm.ScalarMappable(cmap=cmap_on_tissue_obj, norm=norm_on_tissue)
    sm_on_tissue.set_array([])
    plt.colorbar(sm_on_tissue, ax=ax, label="On-Tissue Intensity Sum")

    sm_non_tissue = plt.cm.ScalarMappable(cmap=cmap_non_tissue_obj, norm=norm_non_tissue)
    sm_non_tissue.set_array([])
    plt.colorbar(sm_non_tissue, ax=ax, label="Non-Tissue Intensity Sum")

    # Final plot settings
    ax.set_aspect('equal')
    ax.set_xlabel("X Coordinate (μm)")
    ax.set_ylabel("Y Coordinate (μm)")
    ax.set_title("m/z Centroids with Margin Lines and Image Background")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [24]:
plot_mz_centroids_with_margin_and_mask_contours(
    df,
    image,
    mask,
    cmap_on_tissue="viridis",
    cmap_non_tissue="plasma",
    square_size=0.5,
    circle_size=0.5,
    figsize=(6, 4),
    show_margin=False,
    show_mask_contours=True,
    image_alpha=0.3,
    margin_linewidth=1.5,
    contour_color="red"
)

In [25]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
from skimage import measure

def plot_mz_centroids_with_margin_and_mask_contours(
    df,
    image,
    mask,
    cmap_on_tissue="viridis",
    cmap_non_tissue="plasma",
    square_size=100,
    circle_size=50,
    figsize=(10, 8),
    show_margin=False,
    show_mask_contours=True,
    image_alpha=0.3,
    margin_linewidth=1.5,
    contour_color="red"
):
    """
    Plot centroid heatmap for each m/z using on-tissue squares and non-tissue circles.
    Optionally overlay the original image (faded) and polygon margin contours from mask.
    Intensities are log-scaled before color mapping.
    """
    required_cols = [
        "on_tissue_centroid_x", "on_tissue_centroid_y", "on_tissue_sum",
        "non_tissue_centroid_x", "non_tissue_centroid_y", "non_tissue_sum"
    ]
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")

    # Apply log1p to intensity values
    log_on_tissue = np.log1p(df["on_tissue_sum"])
    log_non_tissue = np.log1p(df["non_tissue_sum"])

    norm_on_tissue = plt.Normalize(vmin=log_on_tissue.min(), vmax=log_on_tissue.max())
    norm_non_tissue = plt.Normalize(vmin=log_non_tissue.min(), vmax=log_non_tissue.max())

    cmap_on_tissue_obj = plt.colormaps[cmap_on_tissue]
    cmap_non_tissue_obj = plt.colormaps[cmap_non_tissue]

    fig, ax = plt.subplots(figsize=figsize)

    # Show background image with alpha
    ax.imshow(image, cmap='gray', alpha=image_alpha)

    # Plot centroids
    for i, row in df.iterrows():
        if not np.isnan(row["on_tissue_centroid_x"]) and not np.isnan(row["on_tissue_centroid_y"]):
            color = cmap_on_tissue_obj(norm_on_tissue(log_on_tissue.iloc[i]))
            square = patches.Rectangle(
                (row["on_tissue_centroid_x"] - square_size / 2, row["on_tissue_centroid_y"] - square_size / 2),
                square_size, square_size,
                linewidth=0.5, edgecolor="black", facecolor=color, alpha=0.8
            )
            ax.add_patch(square)

        if not np.isnan(row["non_tissue_centroid_x"]) and not np.isnan(row["non_tissue_centroid_y"]):
            color = cmap_non_tissue_obj(norm_non_tissue(log_non_tissue.iloc[i]))
            circle = patches.Circle(
                (row["non_tissue_centroid_x"], row["non_tissue_centroid_y"]),
                radius=circle_size / 2,
                linewidth=0.5, edgecolor="black", facecolor=color, alpha=0.8
            )
            ax.add_patch(circle)

    # Plot mask contours
    if show_mask_contours and mask is not None:
        contours = measure.find_contours(mask, level=0.5)
        for contour in contours:
            ax.plot(contour[:, 1], contour[:, 0], linewidth=margin_linewidth, color=contour_color)

    # Colorbars
    sm_on_tissue = plt.cm.ScalarMappable(cmap=cmap_on_tissue_obj, norm=norm_on_tissue)
    sm_on_tissue.set_array([])
    plt.colorbar(sm_on_tissue, ax=ax, label="log(1 + On-Tissue Intensity Sum)")

    sm_non_tissue = plt.cm.ScalarMappable(cmap=cmap_non_tissue_obj, norm=norm_non_tissue)
    sm_non_tissue.set_array([])
    plt.colorbar(sm_non_tissue, ax=ax, label="log(1 + Non-Tissue Intensity Sum)")

    # Final plot settings
    ax.set_aspect('equal')
    ax.set_xlabel("X Coordinate (μm)")
    ax.set_ylabel("Y Coordinate (μm)")
    ax.set_title("m/z Centroids with Mask Contours and Log-Scaled Intensities")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [26]:
plot_mz_centroids_with_margin_and_mask_contours(
    df,
    image,
    mask,
    square_size=1,
    circle_size=1,
    figsize=(6, 4),
    show_margin=False,
    show_mask_contours=True,
    image_alpha=0.3,
    margin_linewidth=1.5,
    contour_color="red"
)

In [27]:
import numpy as np
import pandas as pd
from scipy.stats import entropy
from libpysal.weights import DistanceBand
from libpysal.weights import KNN
from esda.moran import Moran
from tqdm import tqdm

def compute_spatial_entropy(intensities):
    intensities = np.array(intensities, dtype=float)
    intensities = intensities[intensities > 0]
    if len(intensities) == 0:
        return 0
    p = intensities / intensities.sum()
    return entropy(p)


def compute_morans_I(x_coords, y_coords, intensities, k=8):
    coords = list(zip(x_coords, y_coords))
    try:
        w = KNN(coords, k=k)
        return Moran(intensities, w).I
    except Exception as e:
        print("Failed with error:", e)
        return np.nan

def analyze_scatter_wide_format(adata, k_neighbors=8):
    num_mz = adata.shape[1]
    mz_values = adata.var["mzs"].values  # <-- Use "mzs"

    rows = []
    for mz_index in tqdm(range(num_mz), desc="Processing m/z features"):
        row = {"mz": mz_values[mz_index]}
        for flag, region in zip([1, 0], ["tissue", "background"]):
            subset = adata[adata.obs["tissue"] == flag]
            intensities = subset.X[:, mz_index].toarray().flatten() if hasattr(subset.X, "toarray") else subset.X[:, mz_index].flatten()
            x = subset.obs["x"].values
            y = subset.obs["y"].values

            row[f"spatial_entropy_{region}"] = compute_spatial_entropy(intensities)
            row[f"moran_I_{region}"] = compute_morans_I(x, y, intensities, k=k_neighbors)

        rows.append(row)

    return pd.DataFrame(rows)

In [28]:
"""
Moran's I and Spatial Entropy Analysis
This code computes Moran's I and spatial entropy for each m/z feature in the provided AnnData object.   
Moran's I is a measure of spatial autocorrelation, while spatial entropy quantifies the distribution of intensities. 
Moran's I values close to 1 indicate clustering, while values close to -1 indicate dispersion.
moran's I is computed using the `libpysal` library, which requires spatial coordinates and intensities.
Spatial entropy values range from 0 (uniform distribution) to log(n) (maximal entropy), where n is the number of pixels.   
spatial entropy is computed using the `scipy.stats.entropy` function, which requires the input to be a probability distribution.
The analysis is performed separately for tissue and background regions, and results are stored in a DataFrame.
The DataFrame contains the m/z values, spatial entropy, and Moran's I for both regions.
"""

"\nMoran's I and Spatial Entropy Analysis\nThis code computes Moran's I and spatial entropy for each m/z feature in the provided AnnData object.   \nMoran's I is a measure of spatial autocorrelation, while spatial entropy quantifies the distribution of intensities. \nMoran's I values close to 1 indicate clustering, while values close to -1 indicate dispersion.\nmoran's I is computed using the `libpysal` library, which requires spatial coordinates and intensities.\nSpatial entropy values range from 0 (uniform distribution) to log(n) (maximal entropy), where n is the number of pixels.   \nspatial entropy is computed using the `scipy.stats.entropy` function, which requires the input to be a probability distribution.\nThe analysis is performed separately for tissue and background regions, and results are stored in a DataFrame.\nThe DataFrame contains the m/z values, spatial entropy, and Moran's I for both regions.\n"

In [29]:
# Run it
scatter_wide_df = analyze_scatter_wide_format(adata, k_neighbors=8)

# Save to CSV (optional)
scatter_wide_df.to_csv("pixel_area_summary.csv", index=False)

# Preview
print(scatter_wide_df.head())

Processing m/z features: 100%|██████████| 1000/1000 [07:02<00:00,  2.37it/s]

         mz  spatial_entropy_tissue  moran_I_tissue  \
0  136.0150                8.402684        0.415658
1  136.0608                8.702899        0.262929
2  137.0251                8.616154        0.549667
3  138.0287                8.596314        0.508409
4  139.0359                8.537266        0.363029

   spatial_entropy_background  moran_I_background
0                    9.055275            0.493544
1                    8.685133            0.494965
2                    8.950049            0.721676
3                    8.989311            0.701255
4                    9.013560            0.650540

In [30]:
import matplotlib.pyplot as plt
import seaborn as sns

# Create a DataFrame from the results
pixel_area_summary = pd.read_csv("pixel_area_summary.csv")

# Set up the figure size and layout
plt.figure(figsize=(8, 100))

# Plot heatmap for spatial entropy
sns.heatmap(scatter_wide_df[['spatial_entropy_tissue', 'spatial_entropy_background']].set_index(pixel_area_summary['mz']),
            cmap='coolwarm', annot=True, fmt=".2f", cbar=True, xticklabels=True, yticklabels=True)

plt.title("Spatial Entropy for Tissue vs. Background")
plt.xlabel("Region")
plt.ylabel("m/z")
plt.show()

In [31]:
# Plotting Spatial Entropy vs Moran's I for Tissue
plt.figure(figsize=(10, 6))

sns.scatterplot(data=pixel_area_summary, x="spatial_entropy_tissue", y="moran_I_tissue", hue="mz", palette="viridis")

plt.title("Spatial Entropy vs Moran's I for Tissue")
plt.xlabel("Spatial Entropy")
plt.ylabel("Moran's I")
plt.legend(title="m/z", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# Plotting Spatial Entropy vs Moran's I for Background
plt.figure(figsize=(10, 6))

sns.scatterplot(data=pixel_area_summary, x="spatial_entropy_background", y="moran_I_background", hue="mz", palette="viridis")

plt.title("Spatial Entropy vs Moran's I for Background")
plt.xlabel("Spatial Entropy")
plt.ylabel("Moran's I")
plt.legend(title="m/z", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

In [32]:
# Plotting Histograms of Spatial Entropy
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
sns.histplot(pixel_area_summary["spatial_entropy_tissue"], bins=30, kde=True, color='blue', label='Tissue')
sns.histplot(pixel_area_summary["spatial_entropy_background"], bins=30, kde=True, color='red', label='Background')
plt.title("Histogram of Spatial Entropy")
plt.xlabel("Spatial Entropy")
plt.ylabel("Frequency")
plt.legend()

# Plotting Histograms of Moran's I
plt.subplot(1, 2, 2)
sns.histplot(pixel_area_summary["moran_I_tissue"].dropna(), bins=30, kde=True, color='blue', label='Tissue')
sns.histplot(pixel_area_summary["moran_I_background"].dropna(), bins=30, kde=True, color='red', label='Background')
plt.title("Histogram of Moran's I")
plt.xlabel("Moran's I")
plt.ylabel("Frequency")
plt.legend()

plt.tight_layout()
plt.show()

In [33]:
scatter_wide_df['moran_I_diff'] = scatter_wide_df['moran_I_tissue'] - scatter_wide_df['moran_I_background']
top_moran_I = scatter_wide_df.sort_values(by='moran_I_diff', ascending=False).head(10)

In [34]:
scatter_wide_df['entropy_diff'] = scatter_wide_df['spatial_entropy_background'] - scatter_wide_df['spatial_entropy_tissue']
top_entropy_diff = scatter_wide_df.sort_values(by='entropy_diff', ascending=False).head(10)

In [35]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(scatter_wide_df['spatial_entropy_tissue'], scatter_wide_df['moran_I_tissue'], label='Tissue', alpha=0.6)
plt.scatter(scatter_wide_df['spatial_entropy_background'], scatter_wide_df['moran_I_background'], label='Background', alpha=0.6, color='orange')
plt.xlabel("Spatial Entropy")
plt.ylabel("Moran's I")
plt.title("Spatial Statistics per m/z")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

In [36]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
plt.scatter(scatter_wide_df['spatial_entropy_tissue'], scatter_wide_df['moran_I_tissue'], label='Tissue', alpha=0.6)
plt.scatter(scatter_wide_df['spatial_entropy_background'], scatter_wide_df['moran_I_background'], label='Background', alpha=0.6, color='orange')

# Annotate each point with m/z value
for i, row in scatter_wide_df.iterrows():
    mz_label = f"{row['mz']:.1f}"  # format to 1 decimal
    plt.annotate(mz_label,
                 (row['spatial_entropy_tissue'], row['moran_I_tissue']),
                 textcoords="offset points",
                 xytext=(0, 4),
                 ha='center',
                 fontsize=6,
                 color='blue')
    plt.annotate(mz_label,
                 (row['spatial_entropy_background'], row['moran_I_background']),
                 textcoords="offset points",
                 xytext=(0, 4),
                 ha='center',
                 fontsize=6,
                 color='darkorange')

plt.xlabel("Spatial Entropy")
plt.ylabel("Moran's I")
plt.title("Spatial Statistics per m/z")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

In [37]:
import numpy as np
import pandas as pd
from tqdm import tqdm

def compute_intensity_metrics(adata):
    tissue_mask = adata.obs['tissue'] == 1
    background_mask = adata.obs['tissue'] == 0

    X = adata.X
    if hasattr(X, "toarray"):  # If sparse matrix
        X = X.toarray()

    mean_tissue = np.mean(X[tissue_mask], axis=0)
    mean_background = np.mean(X[background_mask], axis=0)

    total_tissue = np.sum(X[tissue_mask], axis=0)
    total_background = np.sum(X[background_mask], axis=0)

    with np.errstate(divide='ignore', invalid='ignore'):
        ratio = np.divide(total_tissue, total_background)
        ratio[np.isnan(ratio)] = 0
        ratio[np.isinf(ratio)] = 0

    df = pd.DataFrame({
        "mz": adata.var["mzs"].values,
        "mean_intensity_tissue": mean_tissue,
        "mean_intensity_background": mean_background,
        "total_intensity_tissue": total_tissue,
        "total_intensity_background": total_background,
        "tissue_to_background_ratio": ratio
    })

    return df

In [38]:
intensity_df = compute_intensity_metrics(adata)

In [39]:
results_df = scatter_wide_df.merge(intensity_df, on="mz")

In [40]:
import matplotlib.pyplot as plt

def plot_intensity_vs_moransI(df):
    plt.figure(figsize=(10, 6))
    
    scatter = plt.scatter(
        df["tissue_to_background_ratio"],
        df["moran_I_tissue"],
        c=df["spatial_entropy_tissue"],
        s=np.clip(df["total_intensity_tissue"] / 1e5, 10, 200),  # scale size
        cmap="viridis",
        alpha=0.8,
        edgecolor='k',
        linewidth=0.5
    )

    plt.xlabel("Tissue-to-Background Intensity Ratio")
    plt.ylabel("Moran's I (Tissue)")
    plt.title("m/z Features: Spatial Autocorrelation vs. Intensity")
    cbar = plt.colorbar(scatter)
    cbar.set_label("Spatial Entropy (Tissue)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [41]:
plot_intensity_vs_moransI(results_df)

In [42]:
import matplotlib.pyplot as plt

def plot_intensity_vs_moransI_with_labels(df, top_n=10, score_fn=None):
    plt.figure(figsize=(10, 6))

    # Compute a custom score if not provided
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["tissue_to_background_ratio"] / (row["spatial_entropy_tissue"] + 1e-6)
    
    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    scatter = plt.scatter(
        df["tissue_to_background_ratio"],
        df["moran_I_tissue"],
        c=df["spatial_entropy_tissue"],
        s=np.clip(df["total_intensity_tissue"] / 1e5, 10, 200),
        cmap="viridis",
        alpha=0.8,
        edgecolor='k',
        linewidth=0.5
    )

    # Annotate top N points
    top_rows = df.nlargest(top_n, "score")
    for _, row in top_rows.iterrows():
        plt.annotate(
            f"{row['mz']:.1f}",
            (row["tissue_to_background_ratio"], row["moran_I_tissue"]),
            fontsize=9,
            xytext=(3, 3),
            textcoords='offset points'
        )

    plt.xlabel("Tissue-to-Background Intensity Ratio")
    plt.ylabel("Moran's I (Tissue)")
    plt.title(f"Top {top_n} m/z Features by Spatial-Intensity Score")
    cbar = plt.colorbar(scatter)
    cbar.set_label("Spatial Entropy (Tissue)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [43]:
"""
this function plots the relationship between tissue-to-background intensity ratio and Moran's I for m/z features.
It uses a scatter plot where the size of each point is proportional to the total intensity in tissue, and the color represents spatial entropy.
The function also annotates the top N m/z features based on a custom score, which is calculated as the product of Moran's I and the tissue-to-background ratio, normalized by spatial entropy.
The score is designed to highlight features that are both spatially autocorrelated and have a high intensity ratio.
The function allows for customization of the scoring function, enabling users to define their own criteria for selecting top features.  

"""

"\nthis function plots the relationship between tissue-to-background intensity ratio and Moran's I for m/z features.\nIt uses a scatter plot where the size of each point is proportional to the total intensity in tissue, and the color represents spatial entropy.\nThe function also annotates the top N m/z features based on a custom score, which is calculated as the product of Moran's I and the tissue-to-background ratio, normalized by spatial entropy.\nThe score is designed to highlight features that are both spatially autocorrelated and have a high intensity ratio.\nThe function allows for customization of the scoring function, enabling users to define their own criteria for selecting top features.  \n\n"

In [44]:
plot_intensity_vs_moransI_with_labels(results_df, top_n=50)

In [45]:
import numpy as np
import matplotlib.pyplot as plt

def plot_intensity_vs_moransI_with_labels(df, top_n=10, score_fn=None, background_threshold=1.0):
    plt.figure(figsize=(10, 6))

    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["tissue_to_background_ratio"] / (row["spatial_entropy_tissue"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Define foreground and background based on threshold
    foreground_df = df[df["tissue_to_background_ratio"] >= background_threshold]
    background_df = df[df["tissue_to_background_ratio"] < background_threshold]

    # Plot background with triangle markers
    bg_scatter = plt.scatter(
        background_df["tissue_to_background_ratio"],
        background_df["moran_I_tissue"],
        c=background_df["spatial_entropy_tissue"],
        s=np.clip(background_df["total_intensity_tissue"] / 1e5, 10, 200),
        cmap="viridis",
        alpha=0.6,
        edgecolor='gray',
        linewidth=0.5,
        marker='v',  # triangle down
        label='Background m/z'
    )

    # Plot foreground with circle markers
    fg_scatter = plt.scatter(
        foreground_df["tissue_to_background_ratio"],
        foreground_df["moran_I_tissue"],
        c=foreground_df["spatial_entropy_tissue"],
        s=np.clip(foreground_df["total_intensity_tissue"] / 1e5, 10, 200),
        cmap="viridis",
        alpha=0.8,
        edgecolor='k',
        linewidth=0.5,
        marker='o',
        label='Foreground m/z'
    )

    # Annotate top N points from full dataframe
    top_rows = df.nlargest(top_n, "score")
    for _, row in top_rows.iterrows():
        plt.annotate(
            f"{row['mz']:.1f}",
            (row["tissue_to_background_ratio"], row["moran_I_tissue"]),
            fontsize=9,
            xytext=(3, 3),
            textcoords='offset points'
        )

    plt.xlabel("Tissue-to-Background Intensity Ratio")
    plt.ylabel("Moran's I (Tissue)")
    plt.title(f"Top {top_n} m/z Features by Spatial-Intensity Score")
    cbar = plt.colorbar(fg_scatter)
    cbar.set_label("Spatial Entropy (Tissue)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [46]:
plot_intensity_vs_moransI_with_labels(results_df, top_n=1000, background_threshold=1.0)

In [47]:
results_df

,mz,spatial_entropy_tissue,moran_I_tissue,spatial_entropy_background,moran_I_background,moran_I_diff,entropy_diff,mean_intensity_tissue,mean_intensity_background,total_intensity_tissue,total_intensity_background,tissue_to_background_ratio
0,136.0150,8.402684,0.415658,9.055275,0.493544,-0.077886,0.652591,71.035520,726.022424,507975.0,6863816.0,0.074008
1,136.0608,8.702899,0.262929,8.685133,0.494965,-0.232036,-0.017767,310.487484,160.181828,2220296.0,1514359.0,1.466162
2,137.0251,8.616154,0.549667,8.950049,0.721676,-0.172009,0.333895,3126.452664,42923.353078,22357263.0,405797380.0,0.055095
3,138.0287,8.596314,0.508409,8.989311,0.701255,-0.192846,0.392997,282.315341,3372.242860,2018837.0,31881184.0,0.063324
4,139.0359,8.537266,0.363029,9.013560,0.650540,-0.287511,0.476294,85.411131,728.722763,610775.0,6889345.0,0.088655
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1520.1588,8.673163,0.286352,7.951131,0.600209,-0.313858,-0.722031,96.334778,21.061667,688890.0,199117.0,3.459725
996,1521.1633,8.660768,0.288768,7.961171,0.607453,-0.318685,-0.699598,85.777793,18.931140,613397.0,178975.0,3.427278
997,1522.1682,8.662518,0.290308,7.965635,0.599701,-0.309393,-0.696883,92.776814,20.725407,663447.0,195938.0,3.386005
998,1542.1475,8.677055,0.241838,8.104479,0.533510,-0.291672,-0.572576,76.066844,15.881743,543954.0,150146.0,3.622834
999,1544.1542,8.686549,0.227777,8.051591,0.508433,-0.280656,-0.634958,78.301077,15.354982,559931.0,145166.0,3.857177

In [48]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

def plot_top_mz_by_background_moransI(df, top_n=10, score_fn=None):
    plt.figure(figsize=(10, 6))

    # Default scoring function
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["tissue_to_background_ratio"] / (row["spatial_entropy_tissue"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Select top N rows by score
    top_rows = df.nlargest(top_n, "score")

    # Plot top N as circles
    scatter = plt.scatter(
        top_rows["moran_I_background"],
        top_rows["moran_I_tissue"],
        c=top_rows["spatial_entropy_tissue"],
        s=np.clip(top_rows["total_intensity_tissue"] / 1e5, 10, 200),
        cmap="viridis",
        alpha=0.9,
        edgecolor='black',
        linewidth=0.6,
        marker='o',
        label='Top m/z'
    )

    # Annotate m/z values
    for _, row in top_rows.iterrows():
        plt.annotate(
            f"{row['mz']:.1f}",
            (row["moran_I_background"], row["moran_I_tissue"]),
            fontsize=9,
            xytext=(3, 3),
            textcoords='offset points'
        )

    # Colorbar
    cbar = plt.colorbar(scatter)
    cbar.set_label("Spatial Entropy (Tissue)")

    # Size legend for circle areas (intensity)
    for val in [1e5, 3e5, 5e5]:
        plt.scatter([], [], s=val / 1e5, c='gray', alpha=0.5,
                    label=f"{int(val):,} total intensity")

    # Plot aesthetics
    plt.xlabel("Moran's I (Background)")
    plt.ylabel("Moran's I (Tissue)")
    plt.title(f"Top {top_n} m/z Features by Spatial-Intensity Score")
    plt.legend(title="Circle Size: Intensity", loc='lower right', frameon=True)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

In [49]:
plot_top_mz_by_background_moransI(results_df, top_n=1000,score_fn=None)

In [50]:

# Ensure the image folder exists
os.makedirs(f"images_{foldchange}", exist_ok=True)

# Compute the global spectrum
global_spectrum = adata.X.sum(axis=0).A1 if hasattr(adata.X, "A1") else np.asarray(adata.X.sum(axis=0)).flatten()

# Get indices of m/z values sorted by intensity (descending)
sorted_indices = np.argsort(global_spectrum)[::-1]

# Select indices from 10th to 20th (ranked #10 to #20)
selected_indices = sorted_indices[0:]

# Get corresponding m/z values
selected_mz = adata.var_names[selected_indices].astype(float)

# Modified plotting loop
for mz in selected_mz:
    # Generate figure using your existing function
    fig = plot_mz_across_sample_custom_tic(adata, mz, tol=0.001)  # Modify function to return fig
    
    # Define filename
    filename = f"images_{foldchange}/mz_{mz:.4f}.png"
    
    # Save the figure
    pio.write_image(fig, filename)
    print(f"Saved: {filename}")

Saved: images_3/mz_273.0397.png
Saved: images_3/mz_137.0251.png
Saved: images_3/mz_274.0435.png
Saved: images_3/mz_369.3523.png
Saved: images_3/mz_331.0297.png
Saved: images_3/mz_257.0478.png
Saved: images_3/mz_195.0905.png
Saved: images_3/mz_637.3020.png
Saved: images_3/mz_313.0337.png
Saved: images_3/mz_275.0563.png
Saved: images_3/mz_245.0458.png
Saved: images_3/mz_333.0266.png
Saved: images_3/mz_197.9919.png
Saved: images_3/mz_244.0353.png
Saved: images_3/mz_246.0516.png
Saved: images_3/mz_734.5673.png
Saved: images_3/mz_330.0215.png
Saved: images_3/mz_347.0108.png
Saved: images_3/mz_551.0132.png
Saved: images_3/mz_258.0498.png
Saved: images_3/mz_229.0488.png
Saved: images_3/mz_501.0369.png
Saved: images_3/mz_199.0008.png
Saved: images_3/mz_332.0313.png
Saved: images_3/mz_544.9929.png
Saved: images_3/mz_798.5391.png
Saved: images_3/mz_375.0044.png
Saved: images_3/mz_290.0419.png
Saved: images_3/mz_370.3516.png
Saved: images_3/mz_291.0466.png
Saved: images_3/mz_638.3054.png
Saved: images_3/mz_184.0720.png
Saved: images_3/mz_346.0029.png
Saved: images_3/mz_760.5916.png
Saved: images_3/mz_368.9916.png
Saved: images_3/mz_721.0097.png
Saved: images_3/mz_409.0579.png
Saved: images_3/mz_367.9774.png
Saved: images_3/mz_309.1370.png
Saved: images_3/mz_543.9945.png
Saved: images_3/mz_285.0295.png
Saved: images_3/mz_138.0287.png
Saved: images_3/mz_262.0491.png
Saved: images_3/mz_550.0092.png
Saved: images_3/mz_307.1212.png
Saved: images_3/mz_159.0070.png
Saved: images_3/mz_772.5231.png
Saved: images_3/mz_247.0594.png
Saved: images_3/mz_735.5735.png
Saved: images_3/mz_659.2911.png
Saved: images_3/mz_272.0306.png
Saved: images_3/mz_485.0599.png
Saved: images_3/mz_467.0459.png
Saved: images_3/mz_315.0454.png
Saved: images_3/mz_335.0136.png
Saved: images_3/mz_353.0146.png
Saved: images_3/mz_523.0186.png
Saved: images_3/mz_297.0362.png
Saved: images_3/mz_269.0502.png
Saved: images_3/mz_483.0330.png

KeyboardInterrupt:

In [52]:
features = results_df[[
    "moran_I_tissue",
    "moran_I_background",
    "spatial_entropy_tissue",
    "spatial_entropy_background"
]].dropna()  # Drop m/z features with missing values

In [53]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(features)

In [54]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=5, random_state=42)
clusters = kmeans.fit_predict(X_scaled)

# Add to original dataframe (after aligning indices)
results_df.loc[features.index, 'cluster'] = clusters

In [55]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
scatter = plt.scatter(
    results_df.loc[features.index, "moran_I_background"],
    results_df.loc[features.index, "moran_I_tissue"],
    c=results_df.loc[features.index, "cluster"],
    cmap="tab10",
    s=50,
    edgecolor='k'
)

plt.xlabel("Moran's I (Background)")
plt.ylabel("Moran's I (Tissue)")
plt.title("Clustering of m/z by Spatial Patterns")
plt.colorbar(scatter, label="Cluster ID")
plt.grid(True)
plt.tight_layout()
plt.show()

In [56]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Use the modern colormap accessor
from matplotlib import colormaps

# Create a colormap with N unique cluster colors
unique_clusters = results_df['cluster'].unique()
cmap = colormaps['tab10']  # or 'Set2', 'Dark2', etc.
cluster_colors = results_df.loc[features.index, 'cluster'].map(lambda x: cmap(x / len(unique_clusters))).to_numpy()

# Now plot the clustermap
sns.clustermap(X_scaled, cmap="viridis", row_colors=cluster_colors)
plt.show()

In [57]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Create bin groupings based on Moran's I values
results_df["morans_group_tissue"] = (results_df["moran_I_tissue"] // 0.1).astype(int)
results_df["morans_group_background"] = (results_df["moran_I_background"] // 0.1).astype(int)

# Combine both into a single composite group for more refined clustering
results_df["morans_group_combo"] = results_df["morans_group_tissue"].astype(str) + "_" + results_df["morans_group_background"].astype(str)

# Prepare data for clustering
features = results_df[["moran_I_tissue", "moran_I_background", "spatial_entropy_tissue", "spatial_entropy_background"]]
X_scaled = StandardScaler().fit_transform(features)

# Assign a unique color to each Moran group
group_labels = results_df["morans_group_combo"].astype("category")
group_colors = group_labels.cat.codes
cmap = plt.colormaps['tab20']
row_colors = [cmap(code / group_colors.max()) for code in group_colors]

# Plot the clustermap
sns.clustermap(
    X_scaled,
    cmap="viridis",
    row_colors=np.array(row_colors),
    xticklabels=["Moran I (Tissue)", "Moran I (Background)", "Entropy (Tissue)", "Entropy (Background)"],
    figsize=(10, 10)
)
plt.show()

In [58]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_top_mz_3d(df, top_n=10, score_fn=None):
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Default scoring function
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["tissue_to_background_ratio"] / (row["spatial_entropy_tissue"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Select top N rows by score
    top_rows = df.nlargest(top_n, "score")

    # Data to plot
    x = top_rows["moran_I_background"]
    y = top_rows["moran_I_tissue"]
    z = top_rows["tissue_to_background_ratio"]
    size = np.clip(top_rows["total_intensity_tissue"] / 1e5, 10, 200)
    color = top_rows["spatial_entropy_tissue"]

    # Scatter plot
    sc = ax.scatter(x, y, z, c=color, s=size, cmap='viridis', edgecolor='black', alpha=0.9)

    # Annotate m/z values
    for _, row in top_rows.iterrows():
        ax.text(row["moran_I_background"], row["moran_I_tissue"], row["tissue_to_background_ratio"],
                f"{row['mz']:.1f}", fontsize=9, ha='left', va='bottom')

    # Axes labels
    ax.set_xlabel("Moran's I (Background)")
    ax.set_ylabel("Moran's I (Tissue)")
    ax.set_zlabel("Tissue-to-Background Intensity Ratio")
    ax.set_title(f"Top {top_n} m/z Features (3D View)")

    # Colorbar
    cbar = fig.colorbar(sc, ax=ax, shrink=0.6)
    cbar.set_label("Spatial Entropy (Tissue)")

    plt.tight_layout()
    plt.show()

In [59]:
plot_top_mz_3d(results_df, top_n=1000,score_fn=None)

In [60]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_top_mz_3d(df, top_n=10, score_fn=None):
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Default scoring function
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["tissue_to_background_ratio"] / (row["spatial_entropy_tissue"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Select top N rows by score
    top_rows = df.nlargest(top_n, "score")

    # Data to plot
    x = top_rows["moran_I_background"]
    y = top_rows["moran_I_tissue"]
    z = top_rows["tissue_to_background_ratio"]
    size = np.clip(top_rows["total_intensity_tissue"] / 1e5, 10, 200)
    color = top_rows["spatial_entropy_tissue"]

    # Scatter plot
    sc = ax.scatter(x, y, z, c=color, s=size, cmap='viridis', edgecolor='black', alpha=0.9)

    """# Annotate m/z values
    for _, row in top_rows.iterrows():
        ax.text(row["moran_I_background"], row["moran_I_tissue"], row["tissue_to_background_ratio"],
                f"{row['mz']:.1f}", fontsize=9, ha='left', va='bottom')
    """

    # Axes labels
    ax.set_xlabel("Moran's I (Background)")
    ax.set_ylabel("Moran's I (Tissue)")
    ax.set_zlabel("Tissue-to-Background Intensity Ratio")
    ax.set_title(f"Top {top_n} m/z Features (3D View)")

    # Colorbar
    cbar = fig.colorbar(sc, ax=ax, shrink=0.6)
    cbar.set_label("Spatial Entropy (Tissue)")

    plt.tight_layout()
    plt.show()

In [61]:
plot_top_mz_3d(results_df, top_n=1000,score_fn=None)

In [62]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

def plot_top_mz_3d(df, top_n=10, score_fn=None):
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Default scoring function (note the swapped fields)
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["spatial_entropy_tissue"] / (row["tissue_to_background_ratio"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Select top N rows by score
    top_rows = df.nlargest(top_n, "score")

    # Data to plot
    x = top_rows["moran_I_background"]
    y = top_rows["moran_I_tissue"]
    z = top_rows["spatial_entropy_tissue"]  # Now Z-axis is spatial entropy
    size = np.clip(top_rows["total_intensity_tissue"] / 1e5, 10, 200)
    color = top_rows["tissue_to_background_ratio"]  # Now color reflects tissue/background ratio

    # Scatter plot
    sc = ax.scatter(x, y, z, c=color, s=size, cmap='viridis', edgecolor='black', alpha=0.9)

    # Annotate m/z values
    for _, row in top_rows.iterrows():
        ax.text(row["moran_I_background"], row["moran_I_tissue"], row["spatial_entropy_tissue"],
                f"{row['mz']:.1f}", fontsize=9, ha='left', va='bottom')

    # Axes labels
    ax.set_xlabel("Moran's I (Background)")
    ax.set_ylabel("Moran's I (Tissue)")
    ax.set_zlabel("Spatial Entropy (Tissue)")
    ax.set_title(f"Top {top_n} m/z Features (3D View)")

    # Colorbar
    cbar = fig.colorbar(sc, ax=ax, shrink=0.6)
    cbar.set_label("Tissue-to-Background Intensity Ratio")

    plt.tight_layout()
    plt.show()

In [63]:
plot_top_mz_3d(results_df, top_n=100,score_fn=None)

In [64]:
def plot_top_mz_3d(df, top_n=10, score_fn=None):
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Default scoring function (swapped spatial_entropy and tissue_to_background_ratio)
    if score_fn is None:
        score_fn = lambda row: row["moran_I_tissue"] * row["spatial_entropy_tissue"] / (row["tissue_to_background_ratio"] + 1e-6)

    df = df.copy()
    df["score"] = df.apply(score_fn, axis=1)

    # Select top N rows by score
    top_rows = df.nlargest(top_n, "score")

    # Data to plot
    x = top_rows["moran_I_background"]
    y = top_rows["moran_I_tissue"]
    z = top_rows["spatial_entropy_tissue"]  # Now Z-axis is spatial entropy
    size = np.clip(top_rows["total_intensity_tissue"] / 1e5, 10, 200)
    color = top_rows["tissue_to_background_ratio"]  # Now color reflects tissue/background ratio

    # Scatter plot (no labels)
    sc = ax.scatter(x, y, z, c=color, s=size, cmap='viridis', edgecolor='black', alpha=0.9)

    # Axes labels
    ax.set_xlabel("Moran's I (Background)")
    ax.set_ylabel("Moran's I (Tissue)")
    ax.set_zlabel("Spatial Entropy (Tissue)")
    ax.set_title(f"Top {top_n} m/z Features (3D View)")

    # Colorbar
    cbar = fig.colorbar(sc, ax=ax, shrink=0.6)
    cbar.set_label("Tissue-to-Background Intensity Ratio")

    plt.tight_layout()
    plt.show()

In [65]:
plot_top_mz_3d(results_df, top_n=1000,score_fn=None)

In [66]:
import numpy as np
import pandas as pd
from scipy.stats import skew
from sklearn.preprocessing import StandardScaler
import umap
import hdbscan
from skimage.measure import label, regionprops
from sklearn.metrics import pairwise_distances
from sklearn.decomposition import PCA

# Sample structure of the required data
# Assuming `results_df` has m/z metadata and intensity maps in a dict `intensity_images`
# Each `intensity_images[mz]` is a 2D numpy array of the ion image

# Placeholder: Simulated data structure
np.random.seed(42)
mz_values = np.linspace(100, 1000, 50)
intensity_images = {mz: np.random.rand(50, 50) for mz in mz_values}

# Metrics container
metrics = []

for mz, img in intensity_images.items():
    flat_img = img.flatten()
    
    # Basic intensity stats
    mean_intensity = np.mean(flat_img)
    std_intensity = np.std(flat_img)
    cv = std_intensity / mean_intensity if mean_intensity > 0 else 0
    skewness = skew(flat_img)
    
    # Spatial Entropy
    p = flat_img / flat_img.sum() if flat_img.sum() > 0 else np.ones_like(flat_img) / len(flat_img)
    spatial_entropy = -np.sum(p * np.log2(p + 1e-9))
    
    # Binarize image for region analysis
    binary_img = img > np.percentile(img, 90)
    labeled = label(binary_img)
    props = regionprops(labeled)
    region_area = np.sum([prop.area for prop in props])
    
    # Placeholder Moran's I and Geary's C
    # Normally this requires spatial weights; we'll mock with PCA-based proxy
    coords = np.indices(img.shape).reshape(2, -1).T
    pca = PCA(n_components=1)
    spatial_signal = pca.fit_transform(flat_img.reshape(-1, 1)).flatten()
    dists = pairwise_distances(coords)
    weights = 1 / (dists + 1e-5)
    weights[np.isinf(weights)] = 0
    np.fill_diagonal(weights, 0)

    mean_x = np.mean(spatial_signal)
    diff = spatial_signal - mean_x
    moran_numerator = np.sum(weights * np.outer(diff, diff))
    moran_denominator = np.sum(diff ** 2)
    moran_I = (len(spatial_signal) / np.sum(weights)) * (moran_numerator / moran_denominator)

    geary_numerator = np.sum(weights * (np.subtract.outer(spatial_signal, spatial_signal) ** 2))
    geary_denominator = 2 * np.sum(diff ** 2)
    geary_C = ((len(spatial_signal) - 1) / (2 * np.sum(weights))) * (geary_numerator / geary_denominator)

    metrics.append({
        "mz": mz,
        "mean_intensity": mean_intensity,
        "cv": cv,
        "skewness": skewness,
        "spatial_entropy": spatial_entropy,
        "region_area": region_area,
        "moran_I": moran_I,
        "geary_C": geary_C
    })

# Convert to DataFrame
metrics_df = pd.DataFrame(metrics)

# Normalize
scaler = StandardScaler()
X_scaled = scaler.fit_transform(metrics_df.drop(columns=["mz"]))

# UMAP
umap_model = umap.UMAP(random_state=42)
X_umap = umap_model.fit_transform(X_scaled)

# HDBSCAN
clusterer = hdbscan.HDBSCAN(min_cluster_size=5)
clusters = clusterer.fit_predict(X_scaled)

# Add to DataFrame
metrics_df["cluster"] = clusters
metrics_df["umap1"] = X_umap[:, 0]
metrics_df["umap2"] = X_umap[:, 1]

metrics_df.head()

/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

,mz,mean_intensity,cv,skewness,spatial_entropy,region_area,moran_I,geary_C,cluster,umap1,umap2
0,100.000000,0.498878,0.582962,-0.008044,11.003021,250.0,-0.001236,0.499982,-1,8.347518,2.806942
1,118.367347,0.494786,0.582803,0.015896,11.004135,250.0,-0.000290,0.498590,-1,7.883735,4.148122
2,136.734694,0.493635,0.582754,0.055338,11.007559,250.0,-0.002185,0.501918,-1,7.114465,2.311029
3,155.102041,0.489339,0.579304,0.035365,11.008217,250.0,-0.000859,0.498512,-1,7.581722,3.648052
4,173.469388,0.504624,0.576101,-0.006412,11.010138,250.0,-0.000792,0.498565,-1,6.350266,5.421074

In [67]:
adata.obs.head()

   x  y        TIC sample    batch age_group disease_status  tissue
0  0  0   997479.0    4-3  Slide_3      Aged             AD       0
1  1  0   875098.0    4-3  Slide_3      Aged             AD       0
2  2  0  1357115.0    4-3  Slide_3      Aged             AD       0
3  3  0  1242398.0    4-3  Slide_3      Aged             AD       0
4  4  0   799114.0    4-3  Slide_3      Aged             AD       0

In [68]:
import numpy as np
import pandas as pd
from scipy.stats import entropy, variation, skew
from libpysal.weights import KNN
from esda.moran import Moran
from esda.geary import Geary
from tqdm import tqdm

def compute_spatial_entropy(intensities):
    intensities = np.array(intensities, dtype=float)
    intensities = intensities[intensities > 0]
    if len(intensities) == 0:
        return np.nan
    p = intensities / intensities.sum()
    return entropy(p)

def compute_morans_I(x_coords, y_coords, intensities, k=8):
    coords = list(zip(x_coords, y_coords))
    try:
        w = KNN(coords, k=k)
        return Moran(intensities, w).I
    except Exception as e:
        # Uncomment to debug
        # print(f"Moran's I calculation failed: {e}")
        return np.nan

def compute_gearys_C(x_coords, y_coords, intensities, k=8):
    coords = list(zip(x_coords, y_coords))
    try:
        w = KNN(coords, k=k)
        return Geary(intensities, w).C
    except Exception as e:
        # Uncomment to debug
        # print(f"Geary's C calculation failed: {e}")
        return np.nan

def analyze_metrics(adata, k_neighbors=8):
    num_mz = adata.shape[1]
    mz_values = adata.var["mzs"].values

    rows = []
    for mz_index in tqdm(range(num_mz), desc="Processing m/z features"):
        row = {"mz": mz_values[mz_index]}

        for flag, region in zip([True, False], ["tissue", "background"]):
            subset = adata[adata.obs["tissue"] == flag]
            if subset.shape[0] == 0:
                # No spots for this region
                row[f"moran_I_{region}"] = np.nan
                row[f"geary_C_{region}"] = np.nan
                row[f"entropy_{region}"] = np.nan
                row[f"cv_{region}"] = np.nan
                row[f"skew_{region}"] = np.nan
                row[f"region_size"] = 0 if region == "tissue" else np.nan
                continue

            intensities = subset.X[:, mz_index].toarray().flatten() if hasattr(subset.X, "toarray") else subset.X[:, mz_index].flatten()
            x = subset.obs["x"].values
            y = subset.obs["y"].values

            # Filter out zero intensities for stats like CV and skew only if nonzero values exist
            nonzero_intensities = intensities[intensities > 0]

            row[f"moran_I_{region}"] = compute_morans_I(x, y, intensities, k=k_neighbors)
            row[f"geary_C_{region}"] = compute_gearys_C(x, y, intensities, k=k_neighbors)
            row[f"entropy_{region}"] = compute_spatial_entropy(intensities)

            if len(nonzero_intensities) > 0:
                row[f"cv_{region}"] = variation(nonzero_intensities)
                row[f"skew_{region}"] = skew(nonzero_intensities)
            else:
                row[f"cv_{region}"] = np.nan
                row[f"skew_{region}"] = np.nan

            if region == "tissue":
                row[f"region_size"] = np.sum(intensities > 0)

        rows.append(row)

    df_metrics = pd.DataFrame(rows)
    return df_metrics

In [69]:
# Run analysis
df_metrics = analyze_metrics(adata, k_neighbors=8)

# Drop rows with NaNs if needed (optional)
df_metrics_clean = df_metrics.dropna()

# Normalize & scale
from sklearn.preprocessing import StandardScaler
feature_cols = [col for col in df_metrics_clean.columns if col != "mz"]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_metrics_clean[feature_cols])

# Dimensionality reduction
import umap
reducer = umap.UMAP(random_state=42)
X_umap = reducer.fit_transform(X_scaled)

# Clustering
import hdbscan
clusterer = hdbscan.HDBSCAN(min_cluster_size=5)
clusters = clusterer.fit_predict(X_scaled)

df_metrics_clean["cluster"] = clusters
df_metrics_clean["UMAP1"] = X_umap[:, 0]
df_metrics_clean["UMAP2"] = X_umap[:, 1]

print(df_metrics_clean.head())

Processing m/z features: 100%|██████████| 1000/1000 [24:39<00:00,  1.48s/it]
/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

         mz  moran_I_tissue  geary_C_tissue  entropy_tissue  cv_tissue  \
0  136.0150        0.415658        0.547822        8.402684   0.965441
1  136.0608        0.262929        0.729385        8.702899   0.630088
2  137.0251        0.549667        0.406121        8.616154   0.964382
3  138.0287        0.508409        0.452354        8.596314   0.921969
4  139.0359        0.363029        0.612376        8.537266   0.820836

   skew_tissue  region_size  moran_I_background  geary_C_background  \
0     3.751760         6199            0.493544            0.501015
1     2.034254         7144            0.494965            0.504816
2     7.986627         7151            0.721676            0.275891
3     5.827630         7122            0.701255            0.295633
4     3.310123         6636            0.650540            0.345992

   entropy_background  cv_background  skew_background  cluster     UMAP1  \
0            9.055275       0.428758         0.298775        3  3.199691
1            8.685133       1.103838         5.571330        3 -0.712172
2            8.950049       0.631648         0.599506        3 -0.091298
3            8.989311       0.565567         0.513532        3  0.038182
4            9.013560       0.523155         0.539632        3  1.256523

      UMAP2
0  5.336668
1  9.539952
2  3.746086
3  3.889664
4  5.280160

In [70]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 6))
palette = sns.color_palette("hsv", len(df_metrics_clean["cluster"].unique()))
sns.scatterplot(
    data=df_metrics_clean, 
    x="UMAP1", y="UMAP2", 
    hue="cluster", 
    palette=palette,
    legend='full',
    s=60,
    edgecolor="k"
)
plt.title("UMAP Projection of m/z Feature Metrics")
plt.xlabel("UMAP1")
plt.ylabel("UMAP2")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [71]:
# Optional: filter out noise cluster (-1)
df_clusters_only = df_metrics_clean[df_metrics_clean["cluster"] != -1]

# Group and compute mean
cluster_means = df_clusters_only.groupby("cluster")[
    [col for col in df_clusters_only.columns if col not in ["mz", "UMAP1", "UMAP2", "cluster"]]
].mean()

# Normalize for better heatmap contrast (optional)
cluster_means_norm = (cluster_means - cluster_means.min()) / (cluster_means.max() - cluster_means.min())

plt.figure(figsize=(12, 6))
sns.heatmap(cluster_means_norm, cmap="viridis", annot=True, fmt=".2f")
plt.title("Normalized Mean Metrics per Cluster")
plt.xlabel("Feature")
plt.ylabel("Cluster")
plt.tight_layout()
plt.show()

In [72]:
# For each cluster, print top m/z with highest entropy or other metric
for cluster_id in sorted(df_clusters_only["cluster"].unique()):
    top_mz = df_clusters_only[df_clusters_only["cluster"] == cluster_id].sort_values("entropy_tissue", ascending=False).head(3)
    print(f"Cluster {cluster_id} top m/z by entropy_tissue:")
    print(top_mz[["mz", "entropy_tissue"]])
    print()

Cluster 0 top m/z by entropy_tissue:
           mz  entropy_tissue
125  269.0502        8.476191
203  332.0313        8.469434
210  335.0136        8.445218

Cluster 1 top m/z by entropy_tissue:
           mz  entropy_tissue
433  489.1071        8.489396
520  564.9677        8.455395
307  387.1928        8.424431

Cluster 2 top m/z by entropy_tissue:
           mz  entropy_tissue
786  789.6188        8.654930
572  605.5548        8.649228
784  788.6130        8.648857

Cluster 3 top m/z by entropy_tissue:
           mz  entropy_tissue
82   240.0953        8.824960
64   224.1000        8.818300
788  790.5270        8.813275

In [73]:
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
import seaborn as sns

# Select only numeric feature columns (exclude mz, cluster, UMAP1/2)
feature_cols = [
    col for col in df_metrics_clean.columns 
    if col not in ["mz", "cluster", "UMAP1", "UMAP2"]
]

# Standardize features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_metrics_clean[feature_cols])

# t-SNE embedding
tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
X_tsne = tsne.fit_transform(X_scaled)

# Add t-SNE results to DataFrame
df_metrics_clean["TSNE1"] = X_tsne[:, 0]
df_metrics_clean["TSNE2"] = X_tsne[:, 1]

# Plot
plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=df_metrics_clean,
    x="TSNE1", y="TSNE2",
    hue="cluster",
    palette="tab10",
    s=60,
    edgecolor="k",
    legend="full"
)
plt.title("t-SNE Projection of m/z Feature Metrics")
plt.xlabel("TSNE1")
plt.ylabel("TSNE2")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

/opt/anaconda3/lib/python3.12/site-packages/sklearn/manifold/_t_sne.py:1162: FutureWarning:

'n_iter' was renamed to 'max_iter' in version 1.5 and will be removed in 1.7.

In [74]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import TSNE
import umap
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots


# Step 1: Filter numeric features
feature_cols = [
    col for col in df_metrics_clean.columns 
    if col not in ["mz", "cluster", "UMAP1", "UMAP2", "TSNE1", "TSNE2"]
]

# Step 2: Standardize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_metrics_clean[feature_cols])

# Step 3: Run t-SNE with tuning
tsne = TSNE(n_components=2, random_state=42, perplexity=40, learning_rate=200, n_iter=1000)
X_tsne = tsne.fit_transform(X_scaled)
df_metrics_clean["TSNE1"] = X_tsne[:, 0]
df_metrics_clean["TSNE2"] = X_tsne[:, 1]

# Step 4: Run UMAP again to ensure consistent dimensions and comparison
umap_model = umap.UMAP(n_components=2, random_state=42)
X_umap = umap_model.fit_transform(X_scaled)
df_metrics_clean["UMAP1"] = X_umap[:, 0]
df_metrics_clean["UMAP2"] = X_umap[:, 1]

# Step 5: Plot with Plotly - Side-by-side interactive scatter plots
fig = make_subplots(rows=1, cols=2, subplot_titles=("t-SNE", "UMAP"), shared_yaxes=True)

# t-SNE plot
fig.add_trace(
    go.Scattergl(
        x=df_metrics_clean["TSNE1"],
        y=df_metrics_clean["TSNE2"],
        mode='markers',
        marker=dict(color=df_metrics_clean["cluster"], colorscale='Viridis', showscale=True),
        text=["m/z: {:.4f}".format(mz) for mz in df_metrics_clean["mz"]],
        name="t-SNE"
    ),
    row=1, col=1
)

# UMAP plot
fig.add_trace(
    go.Scattergl(
        x=df_metrics_clean["UMAP1"],
        y=df_metrics_clean["UMAP2"],
        mode='markers',
        marker=dict(color=df_metrics_clean["cluster"], colorscale='Viridis', showscale=False),
        text=["m/z: {:.4f}".format(mz) for mz in df_metrics_clean["mz"]],
        name="UMAP"
    ),
    row=1, col=2
)

fig.update_layout(
    title_text="Comparison of t-SNE and UMAP Projections",
    height=600,
    width=1000,
    showlegend=False
)

fig.update_xaxes(title_text="TSNE1", row=1, col=1)
fig.update_yaxes(title_text="TSNE2", row=1, col=1)
fig.update_xaxes(title_text="UMAP1", row=1, col=2)
fig.update_yaxes(title_text="UMAP2", row=1, col=2)

fig.show()

/opt/anaconda3/lib/python3.12/site-packages/sklearn/manifold/_t_sne.py:1162: FutureWarning:

'n_iter' was renamed to 'max_iter' in version 1.5 and will be removed in 1.7.

/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

In [75]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.manifold import TSNE
import umap
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Step 1: Prepare data
df = df_metrics.copy()
feature_cols = [col for col in df.columns if col not in ["mz", "cluster", "UMAP1", "UMAP2", "TSNE1", "TSNE2"]]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df[feature_cols])

# Step 2: Run dimensionality reductions
tsne_1 = TSNE(n_components=2, perplexity=30, learning_rate=200, random_state=42)
X_tsne_1 = tsne_1.fit_transform(X_scaled)

tsne_2 = TSNE(n_components=2, perplexity=50, learning_rate=50, random_state=42)
X_tsne_2 = tsne_2.fit_transform(X_scaled)

X_umap = umap.UMAP(n_components=2, random_state=42).fit_transform(X_scaled)

# Add to DataFrame
df["TSNE1_a"], df["TSNE2_a"] = X_tsne_1[:, 0], X_tsne_1[:, 1]
df["TSNE1_b"], df["TSNE2_b"] = X_tsne_2[:, 0], X_tsne_2[:, 1]
df["UMAP1"], df["UMAP2"] = X_umap[:, 0], X_umap[:, 1]

# Step 3: Interactive Plotly comparison
fig = make_subplots(rows=1, cols=2, subplot_titles=("t-SNE", "UMAP"), shared_yaxes=True)
color_column = "mz"
# t-SNE trace (initial = model 1)
tsne_trace = go.Scattergl(
    x=df["TSNE1_a"],
    y=df["TSNE2_a"],
    mode='markers',
    marker=dict(color=df[color_column], colorscale="Viridis", size=6, showscale=True),
    text=df["mz"],
    name="t-SNE (p=30, lr=200)"
)

# UMAP trace
umap_trace = go.Scattergl(
    x=df["UMAP1"],
    y=df["UMAP2"],
    mode='markers',
    marker=dict(color=df[color_column], colorscale="Viridis", size=6, showscale=False),
    text=df["mz"],
    name="UMAP"
)

# Add traces
fig.add_trace(tsne_trace, row=1, col=1)
fig.add_trace(umap_trace, row=1, col=2)

# Dropdown for switching t-SNE parameters
fig.update_layout(
    updatemenus=[
        dict(
            type="buttons",
            direction="down",
            buttons=[
                dict(
                    label="t-SNE (p=30, lr=200)",
                    method="restyle",
                    args=[{"x": [df["TSNE1_a"]], "y": [df["TSNE2_a"]]}, [0]]
                ),
                dict(
                    label="t-SNE (p=50, lr=50)",
                    method="restyle",
                    args=[{"x": [df["TSNE1_b"]], "y": [df["TSNE2_b"]]}, [0]]
                ),
            ],
            x=0.05, y=1.2,
            showactive=True
        )
    ]
)

# Layout adjustments
fig.update_layout(
    title="Interactive Comparison of t-SNE and UMAP",
    width=1000,
    height=500
)

fig.show()

/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

In [76]:
from sklearn.cluster import MiniBatchKMeans

# Choose number of clusters
n_clusters = 100  # or any number between 100-200

# Run clustering
kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42, batch_size=100)
df_metrics_clean["cluster"] = kmeans.fit_predict(X_scaled)

In [77]:
import plotly.graph_objs as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=2, subplot_titles=("t-SNE", "UMAP"), shared_yaxes=True)

# t-SNE trace
fig.add_trace(
    go.Scattergl(
        x=df_metrics_clean["TSNE1"],
        y=df_metrics_clean["TSNE2"],
        mode="markers",
        marker=dict(
            color=df_metrics_clean["cluster"],
            colorscale="Viridis",
            size=5,
            showscale=True,
            colorbar=dict(title="Cluster")
        ),
        text=df_metrics_clean["mz"],
        name="t-SNE"
    ),
    row=1, col=1
)

# UMAP trace
fig.add_trace(
    go.Scattergl(
        x=df_metrics_clean["UMAP1"],
        y=df_metrics_clean["UMAP2"],
        mode="markers",
        marker=dict(
            color=df_metrics_clean["cluster"],
            colorscale="Viridis",
            size=5,
            showscale=False
        ),
        text=df_metrics_clean["mz"],
        name="UMAP"
    ),
    row=1, col=2
)

fig.update_layout(title="t-SNE vs UMAP with 150 Clusters", height=600, width=1000)
fig.show()

In [78]:
for cluster_id, group in df_metrics_clean.groupby("cluster"):
    print(f"\nCluster {cluster_id} ({len(group)} m/z features):")
    print(group["mz"].values)

Cluster 0 (14 m/z features):
[229.0488 244.0353 245.0458 246.0516 247.0594 256.0338 257.0478 262.0491
 272.0306 275.0563 289.0389 290.0419 291.0466 292.0531]

Cluster 1 (13 m/z features):
[163.0405 202.1793 203.0369 203.068  214.0577 233.0507 265.0616 275.2736
 342.3255 361.0668 455.0366 457.0507 609.0626]

Cluster 2 (12 m/z features):
[772.5231 773.5307 798.5391 799.5511 800.5515 801.5524 824.5594 846.5322
 848.5533 849.5585 912.4556 966.9248]

Cluster 3 (12 m/z features):
[ 841.0405  859.0277  876.0159  880.0137  882.0225  883.0213  899.0129
  905.032  1033.0245 1051.0231 1072.0057 1255.0399]

Cluster 4 (4 m/z features):
[230.9492 252.9273 268.8998 422.932 ]

Cluster 5 (11 m/z features):
[197.1082 349.039  350.0839 386.9952 407.1967 499.0256 580.9368 786.4932
 837.6503 858.5287 966.5311]

Cluster 6 (15 m/z features):
[364.0681 387.1928 389.9643 392.0363 465.1795 473.1425 537.9825 560.0797
 587.9561 588.9623 737.9794 740.9714 743.9934 744.9822 934.9747]

Cluster 7 (1 m/z features):
[451.161]

Cluster 8 (16 m/z features):
[268.1057 270.1184 328.3184 355.3483 361.2742 385.2707 464.3135 466.3291
 744.5532 747.5825 763.6049 778.5663 786.6035 793.5621 810.6019 811.5966]

Cluster 9 (13 m/z features):
[258.0498 339.2947 354.3367 367.3328 605.5548 606.5544 620.6035 630.6179
 631.6271 646.6168 648.6279 728.5562 730.5729]

Cluster 10 (2 m/z features):
[836.6271 850.4877]

Cluster 11 (19 m/z features):
[185.0686 278.0479 279.0973 301.0227 310.0742 311.1516 325.004  333.1222
 334.1111 341.0906 344.9885 346.0598 351.1385 409.1727 487.1585 640.3147
 653.0389 655.0489 655.3171]

Cluster 12 (11 m/z features):
[196.0981 287.0455 295.0229 317.048  367.9774 372.9863 461.0358 468.0562
 483.033  505.0127 527.0004]

Cluster 13 (15 m/z features):
[187.0399 254.0257 316.209  319.0414 350.0431 363.0524 396.0666 414.0625
 416.0729 440.403  551.0952 561.0825 565.0818 636.0461 751.3358]

Cluster 14 (12 m/z features):
[219.9751 375.0044 449.3544 523.0186 528.0132 529.017  543.9945 544.9929
 548.996  705.0255 720.0018 727.025 ]

Cluster 15 (7 m/z features):
[328.002  364.0014 366.9731 383.9606 384.9708 391.9758 412.9616]

Cluster 16 (17 m/z features):
[373.9904 395.9797 396.9882 530.0217 552.0181 661.0524 677.0327 683.0331
 698.0059 699.0099 704.0173 706.0229 722.0066 725.0014 726.0129 897.011
 903.0234]

Cluster 17 (17 m/z features):
[219.063  277.0659 307.0371 353.0721 355.0768 366.0703 384.0804 394.0619
 405.1816 441.063  443.0551 450.0488 547.0845 575.0688 591.0623 593.0809
 603.0646]

Cluster 18 (10 m/z features):
[189.0757 260.0386 370.0575 370.982  408.0254 428.0476 564.0651 639.3097
 752.9524 758.9668]

Cluster 19 (11 m/z features):
[318.0517 360.0056 366.0285 553.9998 574.9745 645.0522 647.0388 711.0204
 713.001  773.0815 835.3016]

Cluster 20 (8 m/z features):
[213.9619 235.9458 350.9995 484.0411 500.0308 560.9688 582.959  583.961 ]

Cluster 21 (6 m/z features):
[406.0697 452.061  459.0317 473.038  589.0684 594.0808]

Cluster 22 (8 m/z features):
[392.9619 411.9507 559.9661 564.9677 567.9813 568.9807 735.9644 736.9716]

Cluster 23 (15 m/z features):
[136.0608 404.9267 597.9289 759.5684 764.6067 780.5778 797.577  802.4798
 804.4848 818.5523 825.5629 835.6044 836.5261 837.5366 950.9432]

Cluster 24 (16 m/z features):
[176.0111 201.0571 230.0543 243.0269 264.0603 306.0433 382.0721 383.0799
 393.0658 397.0578 398.0677 399.0702 410.0475 603.5365 621.0713 637.0596]

Cluster 25 (13 m/z features):
[427.9302 530.3032 753.5875 754.5827 756.551  757.5601 769.5648 770.5583
 782.5675 783.5694 808.5768 831.5201 874.5046]

Cluster 26 (3 m/z features):
[397.9893 813.0526 863.0378]

Cluster 27 (6 m/z features):
[573.9908 807.038  829.029  834.2923 836.2988 856.0102]

Cluster 28 (8 m/z features):
[195.0905 269.0502 307.1212 309.137  335.0136 352.0063 638.3054 659.2911]

Cluster 29 (15 m/z features):
[198.121  242.1088 250.0883 269.1003 366.1371 626.5129 697.4753 713.4442
 714.4474 762.4953 765.5245 787.4854 812.5174 834.5319 958.5659]

Cluster 30 (11 m/z features):
[203.2236 224.1    256.0827 264.1099 283.0942 284.0794 327.2354 625.5188
 649.5179 790.527  806.5172]

Cluster 31 (16 m/z features):
[480.3211 562.3243 703.5655 782.653  792.6645 808.6637 810.6888 832.6662
 838.6237 839.6229 848.6424 849.6475 850.6533 852.6411 864.6292 866.646 ]

Cluster 32 (15 m/z features):
[156.0424 172.054  190.0676 294.0637 331.117  365.97   446.0654 449.1508
 463.1664 485.358  498.002  540.4258 716.9822 717.9764 813.3141]

Cluster 33 (2 m/z features):
[284.0206 346.0029]

Cluster 34 (22 m/z features):
[136.015  154.0255 155.035  165.02   268.0413 270.0538 274.2748 308.1168
 310.1357 413.2633 482.0163 486.0605 502.0343 503.0424 520.9935 524.0176
 542.9766 581.2419 599.3925 660.2892 676.2717 718.9828]

Cluster 35 (7 m/z features):
[229.0025 357.987  872.9946 874.014  879.0167 889.9894 894.9983]

Cluster 36 (13 m/z features):
[213.056  217.0514 241.0502 248.0624 365.0685 367.0818 395.068  423.0667
 425.0628 439.057  451.059  465.0382 619.0599]

Cluster 38 (34 m/z features):
[203.18   259.2436 284.2929 313.2732 341.3084 386.2827 508.2855 518.326
 549.5485 579.5273 599.4994 611.5435 629.5439 653.5411 655.563  718.538
 720.5643 724.5195 733.5854 740.4961 741.4946 749.5297 751.5392 764.5222
 774.5268 775.5356 777.5555 784.572  788.5027 807.5094 809.5828 815.532
 828.5011 832.5781]

Cluster 39 (6 m/z features):
[302.0159 406.9501 407.9548 408.9519 424.9368 428.9334]

Cluster 40 (14 m/z features):
[280.0902 340.3089 353.3347 389.3006 564.2518 604.5345 742.5174 758.5699
 767.5312 787.5956 804.5468 812.592  816.5298 834.595 ]

Cluster 41 (15 m/z features):
[178.0269 199.0439 200.0492 211.0595 215.0298 216.0426 316.0537 387.0725
 401.0788 405.0673 422.0525 444.0666 445.0608 487.0621 545.0745]

Cluster 42 (7 m/z features):
[348.0689 402.9348 464.0783 542.0715 580.032  602.0143 702.0723]

Cluster 43 (5 m/z features):
[231.9456 232.9441 251.9214 267.8913 444.9043]

Cluster 44 (5 m/z features):
[445.1529 775.098  790.3306 791.0672 814.3231]

Cluster 45 (9 m/z features):
[ 869.0128  891.9965  917.9902  920.0021 1055.0187 1065.9956 1071.0052
 1093.9899 1095.0011]

Cluster 46 (15 m/z features):
[218.056  228.0455 255.0287 261.0393 263.0537 271.0377 276.0565 288.0302
 315.0454 329.0229 381.0657 411.065  427.0635 449.049  675.2615]

Cluster 47 (9 m/z features):
[ 763.967   764.9689  888.9867  911.9808  912.9832  913.9861  916.985
  920.9955 1088.9844]

Cluster 48 (11 m/z features):
[139.0359 177.0146 227.0378 286.0403 293.0538 308.0478 312.0225 400.0739
 421.0485 426.0626 469.058 ]

Cluster 49 (5 m/z features):
[304.0301 321.0332 349.994  420.0367 438.0421]

Cluster 50 (4 m/z features):
[365.0184 693.0084 713.9808 714.9844]

Cluster 51 (10 m/z features):
[258.113  397.3363 502.2887 526.299  560.3174 702.5467 729.5701 766.5276
 790.6252 794.5587]

Cluster 52 (16 m/z features):
[196.9856 354.008  361.0087 376.0027 511.0158 531.0173 553.0034 571.9841
 572.9871 659.0333 660.0424 676.022  681.0148 682.0179 687.0215 728.026 ]

Cluster 53 (7 m/z features):
[352.3177 587.5433 621.6046 634.6154 788.613  789.6188 822.6423]

Cluster 54 (1 m/z features):
[347.0108]

Cluster 55 (15 m/z features):
[251.0421 267.0272 371.9835 488.0165 509.0142 525.9985 537.0208 665.0323
 675.012  680.0125 696.9911 702.0029 708.0082 709.0077 749.0038]

Cluster 56 (11 m/z features):
[355.9988 512.0132 513.0214 532.0038 533.0012 667.0381 686.0261 688.0289
 723.9907 747.9885 857.0198]

Cluster 57 (23 m/z features):
[199.9998 336.0213 356.9964 369.9904 460.0332 489.0298 504.0026 506.0141
 507.0164 546.9926 547.9938 663.0409 678.0215 679.0223 684.0262 685.0201
 691.9973 700.003  701.0084 703.0097 707.0211 715.9888 723.0042]

Cluster 58 (12 m/z features):
[220.0723 232.0653 243.0677 249.0743 273.2634 298.0454 299.0563 347.0677
 413.068  437.0375 481.0294 635.0444]

Cluster 59 (14 m/z features):
[231.0686 259.0608 264.2661 282.2793 326.304  356.3532 368.3461 369.3523
 370.3516 385.3478 396.31   398.3291 746.58   750.5461]

Cluster 60 (9 m/z features):
[534.2923 731.6    732.6042 734.5673 735.5735 736.5804 760.5916 761.5914
 762.5918]

Cluster 61 (8 m/z features):
[222.0783 226.1111 233.0774 266.072  303.2312 723.4974 725.5188 791.5339]

Cluster 62 (12 m/z features):
[160.0107 337.0225 447.0619 448.041  490.0345 491.0306 525.0175 599.0718
 658.0248 666.0349 689.0372 729.0159]

Cluster 63 (4 m/z features):
[496.3372 497.3396 522.3597 524.3675]

Cluster 64 (6 m/z features):
[851.0099 861.0252 877.0113 878.0072 884.0076 885.0075]

Cluster 65 (4 m/z features):
[361.9717 362.9775 741.9821 742.9933]

Cluster 66 (9 m/z features):
[339.0374 463.0443 471.0364 557.0665 576.0744 597.0643 615.0577 617.0518
 641.0331]

Cluster 67 (15 m/z features):
[778.4689 781.5784 789.4961 805.5502 808.5023 813.5133 826.4664 854.4907
 856.5085 876.5071 897.4819 926.5427 950.5529 963.4792 964.496 ]

Cluster 68 (6 m/z features):
[ 898.0182  901.004   902.0134  904.034  1078.0327 1079.0364]

Cluster 69 (4 m/z features):
[332.3338 550.0092 551.0132 721.0097]

Cluster 70 (23 m/z features):
[184.072  222.0327 273.2201 739.4628 771.5526 785.5751 796.5415 802.5665
 822.5297 828.5639 829.5068 832.515  833.5862 847.5362 850.5641 852.4881
 875.4991 896.488  925.5197 932.5598 948.5346 974.5565 975.5518]

Cluster 71 (3 m/z features):
[423.9832 617.9849 664.1207]

Cluster 72 (15 m/z features):
[ 296.0663  774.94    820.5273  821.5281  826.5668  827.5714  844.5262
  845.529   868.4722  872.556  1494.1565 1495.1523 1520.1588 1521.1633
 1522.1682]

Cluster 73 (1 m/z features):
[866.4661]

Cluster 74 (17 m/z features):
[173.0578 202.0613 296.0287 305.0435 309.0449 311.013  337.0706 412.0659
 415.0671 429.069  433.0486 442.063  466.0368 535.09   563.0803 638.0627
 639.0779]

Cluster 75 (7 m/z features):
[ 881.0243 1057.0334 1067.0081 1074.0223 1077.0151 1080.0408 1249.03  ]

Cluster 76 (11 m/z features):
[137.0251 138.0287 159.007  273.0397 274.0435 297.0362 313.0337 314.0387
 409.0579 467.0459 485.0599]

Cluster 77 (13 m/z features):
[239.0343 380.0606 391.0428 407.0558 424.0641 453.0549 470.0609 531.0776
 559.0778 585.0588 587.0671 601.0612 604.0622]

Cluster 78 (3 m/z features):
[201.9372 443.901  790.9199]

Cluster 79 (5 m/z features):
[835.0365 858.0298 900.0081 924.0059 925.0016]

Cluster 80 (13 m/z features):
[365.3188 366.3293 371.3606 383.3277 384.3286 577.5215 627.5297 651.5335
 652.537  752.557  768.5477 792.5538 830.5131]

Cluster 81 (12 m/z features):
[197.9919 199.0008 285.0295 330.0215 331.0297 332.0313 333.0266 353.0146
 355.0027 368.9916 501.0369 637.302 ]

Cluster 82 (12 m/z features):
[386.0081 388.9561 405.9378 477.0158 489.1071 561.9723 562.9767 581.9474
 584.9532 677.2827 738.9761 759.9656]

Cluster 83 (11 m/z features):
[ 837.0439  853.0236  940.9789 1039.0396 1050.0183 1052.0283 1056.0259
 1068.0066 1075.01   1095.9983 1271.0072]

Cluster 84 (7 m/z features):
[ 220.98    662.0519  875.0211  890.9927  896.0043  918.9958 1073.021 ]

Cluster 85 (7 m/z features):
[179.0362 316.1003 332.095  335.0695 582.253  607.0599 661.2994]

Cluster 86 (7 m/z features):
[229.9417 402.0237 598.9329 599.9377 600.9327 614.9061 710.485 ]

Cluster 87 (4 m/z features):
[558.954  734.9579 757.9567 882.5672]

Cluster 88 (6 m/z features):
[240.0412 357.0624 541.9698 631.0347 657.0172 664.0419]

Cluster 89 (21 m/z features):
[191.0379 279.0389 339.0857 354.0737 369.0587 377.0703 379.0653 385.0822
 417.071  435.059  440.0549 517.0743 519.0818 549.088  577.0809 579.086
 595.0816 605.0714 620.0598 622.0728 623.0859]

Cluster 90 (3 m/z features):
[462.0395 510.0096 643.0466]

Cluster 91 (2 m/z features):
[214.9722 390.9737]

Cluster 92 (2 m/z features):
[554.2875 650.4418]

Cluster 93 (6 m/z features):
[823.632  840.6227 851.6469 853.6358 865.6309 867.6489]

Cluster 94 (10 m/z features):
[ 805.4882  824.4467  840.4328  853.4827  869.4633  870.4678  873.5623
  913.4582 1542.1475 1544.1542]

Cluster 95 (7 m/z features):
[181.0163 204.0398 371.0661 508.0197 533.0819 581.084  598.057 ]

Cluster 96 (4 m/z features):
[334.0233 376.9855 522.0106 546.0025]

Cluster 97 (5 m/z features):
[192.9801 210.9897 303.0184 348.0119 538.9855]

Cluster 98 (20 m/z features):
[161.1338 180.0717 215.1771 240.0953 242.0613 243.2107 247.2447 255.2101
 257.2299 386.3513 482.3231 548.5356 551.5052 578.5188 623.5002 628.5364
 635.5397 748.5259 776.5574 814.5224]

Cluster 99 (2 m/z features):
[565.9747 566.9828]

In [79]:
clustered_mzs = df_metrics_clean.groupby("cluster")["mz"].apply(list).to_dict()

In [80]:
clustered_mzs[0]  # m/z values in cluster 0
clustered_mzs[1]  # m/z values in cluster 1

[163.0405,
 202.1793,
 203.0369,
 203.068,
 214.0577,
 233.0507,
 265.0616,
 275.2736,
 342.3255,
 361.0668,
 455.0366,
 457.0507,
 609.0626]

In [81]:
df_metrics_clean[["mz", "cluster"]].sort_values("cluster").to_csv("clustered_mzs.csv", index=False)

In [82]:
cluster_counts = df_metrics_clean["cluster"].value_counts().sort_index()
print(cluster_counts)

cluster
0     14
1     13
2     12
3     12
4      4
      ..
95     7
96     4
97     5
98    20
99     2
Name: count, Length: 99, dtype: int64

In [83]:
import os
import plotly.io as pio

# Ensure the image folder exists
os.makedirs(f"images_from_clusters", exist_ok=True)

# Merge cluster info with AnnData's m/z values
mz_cluster_map = dict(zip(df_metrics_clean["mz"].astype(float), df_metrics_clean["cluster"]))

# Compute the global spectrum
global_spectrum = adata.X.sum(axis=0).A1 if hasattr(adata.X, "A1") else np.asarray(adata.X.sum(axis=0)).flatten()

# Get indices of m/z values sorted by intensity (descending)
sorted_indices = np.argsort(global_spectrum)[::-1]

# Select indices of interest (e.g., all, top N, etc.)
selected_indices = sorted_indices[0:]  # You can limit with [10:20] if desired

# Get corresponding m/z values from adata.var
selected_mz = adata.var["mzs"].values[selected_indices].astype(float)

# Generate and save images
for mz in selected_mz:
    if mz not in mz_cluster_map:
        print(f"Skipping m/z {mz:.4f} — not in clustered data.")
        continue

    cluster_id = mz_cluster_map[mz]
    fig = plot_mz_across_sample_custom_tic(adata, mz, tol=0.001)  # Make sure this function returns a Plotly fig

    filename = f"images_from_clusters/cluster_{cluster_id}_mz_{mz:.4f}_.png"
    pio.write_image(fig, filename)
    print(f"Saved: {filename}")

Saved: images_from_clusters/cluster_76_mz_273.0397_.png
Saved: images_from_clusters/cluster_76_mz_137.0251_.png
Saved: images_from_clusters/cluster_76_mz_274.0435_.png
Saved: images_from_clusters/cluster_59_mz_369.3523_.png
Saved: images_from_clusters/cluster_81_mz_331.0297_.png
Saved: images_from_clusters/cluster_0_mz_257.0478_.png
Saved: images_from_clusters/cluster_28_mz_195.0905_.png
Saved: images_from_clusters/cluster_81_mz_637.3020_.png
Saved: images_from_clusters/cluster_76_mz_313.0337_.png
Saved: images_from_clusters/cluster_0_mz_275.0563_.png
Saved: images_from_clusters/cluster_0_mz_245.0458_.png
Saved: images_from_clusters/cluster_81_mz_333.0266_.png
Saved: images_from_clusters/cluster_81_mz_197.9919_.png
Saved: images_from_clusters/cluster_0_mz_244.0353_.png
Saved: images_from_clusters/cluster_0_mz_246.0516_.png
Saved: images_from_clusters/cluster_60_mz_734.5673_.png
Saved: images_from_clusters/cluster_81_mz_330.0215_.png
Saved: images_from_clusters/cluster_54_mz_347.0108_.png
Saved: images_from_clusters/cluster_69_mz_551.0132_.png
Saved: images_from_clusters/cluster_9_mz_258.0498_.png
Saved: images_from_clusters/cluster_0_mz_229.0488_.png
Saved: images_from_clusters/cluster_81_mz_501.0369_.png
Saved: images_from_clusters/cluster_81_mz_199.0008_.png
Saved: images_from_clusters/cluster_81_mz_332.0313_.png
Saved: images_from_clusters/cluster_14_mz_544.9929_.png
Saved: images_from_clusters/cluster_2_mz_798.5391_.png
Saved: images_from_clusters/cluster_14_mz_375.0044_.png
Saved: images_from_clusters/cluster_0_mz_290.0419_.png
Saved: images_from_clusters/cluster_59_mz_370.3516_.png
Saved: images_from_clusters/cluster_0_mz_291.0466_.png
Saved: images_from_clusters/cluster_28_mz_638.3054_.png
Saved: images_from_clusters/cluster_70_mz_184.0720_.png
Saved: images_from_clusters/cluster_33_mz_346.0029_.png
Saved: images_from_clusters/cluster_60_mz_760.5916_.png
Saved: images_from_clusters/cluster_81_mz_368.9916_.png
Saved: images_from_clusters/cluster_69_mz_721.0097_.png
Saved: images_from_clusters/cluster_76_mz_409.0579_.png
Saved: images_from_clusters/cluster_12_mz_367.9774_.png
Saved: images_from_clusters/cluster_28_mz_309.1370_.png
Saved: images_from_clusters/cluster_14_mz_543.9945_.png
Saved: images_from_clusters/cluster_81_mz_285.0295_.png
Saved: images_from_clusters/cluster_76_mz_138.0287_.png
Saved: images_from_clusters/cluster_0_mz_262.0491_.png

KeyboardInterrupt:

In [84]:
import numpy as np
import pandas as pd
from scipy.stats import entropy, variation, skew
from libpysal.weights import KNN
from esda.moran import Moran
from esda.geary import Geary
from tqdm import tqdm

# Define global offsets for common adducts and isotopes
ADDUCTS_AND_ISOTOPES = {
    "has_H_adduct": 1.0073,
    "has_Na_adduct": 22.9898,
    "has_K_adduct": 38.9637,
    "has_Mplus1_isotope": 1.00335,
    "has_Mplus2_isotope": 2.0067,
}

def find_related_mz_features(mz_values, current_mz, tolerance=0.01):
    related_features = {}
    for label, offset in ADDUCTS_AND_ISOTOPES.items():
        target_mz = current_mz + offset
        match = np.any(np.isclose(mz_values, target_mz, atol=tolerance))
        related_features[label] = int(match)
    return related_features

def compute_spatial_entropy(intensities):
    intensities = np.array(intensities, dtype=float)
    intensities = intensities[intensities > 0]
    if len(intensities) == 0:
        return np.nan
    p = intensities / intensities.sum()
    return entropy(p)

def compute_morans_I(x_coords, y_coords, intensities, k=8):
    coords = list(zip(x_coords, y_coords))
    try:
        w = KNN(coords, k=k)
        return Moran(intensities, w).I
    except Exception as e:
        # Uncomment to debug
        # print(f"Moran's I calculation failed: {e}")
        return np.nan

def compute_gearys_C(x_coords, y_coords, intensities, k=8):
    coords = list(zip(x_coords, y_coords))
    try:
        w = KNN(coords, k=k)
        return Geary(intensities, w).C
    except Exception as e:
        # Uncomment to debug
        # print(f"Geary's C calculation failed: {e}")
        return np.nan

def analyze_metrics(adata, k_neighbors=8):
    num_mz = adata.shape[1]
    mz_values = adata.var["mzs"].values

    rows = []
    for mz_index in tqdm(range(num_mz), desc="Processing m/z features"):
        row = {"mz": mz_values[mz_index]}

        for flag, region in zip([True, False], ["tissue", "background"]):
            subset = adata[adata.obs["tissue"] == flag]
            if subset.shape[0] == 0:
                # No spots for this region
                row[f"moran_I_{region}"] = np.nan
                row[f"geary_C_{region}"] = np.nan
                row[f"entropy_{region}"] = np.nan
                row[f"cv_{region}"] = np.nan
                row[f"skew_{region}"] = np.nan
                row[f"region_size"] = 0 if region == "tissue" else np.nan
                continue

            intensities = subset.X[:, mz_index].toarray().flatten() if hasattr(subset.X, "toarray") else subset.X[:, mz_index].flatten()
            x = subset.obs["x"].values
            y = subset.obs["y"].values

            # Filter out zero intensities for stats like CV and skew only if nonzero values exist
            nonzero_intensities = intensities[intensities > 0]

            row[f"moran_I_{region}"] = compute_morans_I(x, y, intensities, k=k_neighbors)
            row[f"geary_C_{region}"] = compute_gearys_C(x, y, intensities, k=k_neighbors)
            row[f"entropy_{region}"] = compute_spatial_entropy(intensities)

            if len(nonzero_intensities) > 0:
                row[f"cv_{region}"] = variation(nonzero_intensities)
                row[f"skew_{region}"] = skew(nonzero_intensities)
            else:
                row[f"cv_{region}"] = np.nan
                row[f"skew_{region}"] = np.nan

            if region == "tissue":
                row[f"region_size"] = np.sum(intensities > 0)

        related_features = find_related_mz_features(mz_values, mz_values[mz_index])
        row.update(related_features)

        rows.append(row)

    df_metrics = pd.DataFrame(rows)
    return df_metrics

In [86]:

# Run analysis
df_metrics = analyze_metrics(adata, k_neighbors=8)

# Drop rows with NaNs if needed (optional)
df_metrics_clean = df_metrics.dropna()

# Normalize & scale
from sklearn.preprocessing import StandardScaler
feature_cols = [col for col in df_metrics_clean.columns if col != "mz"]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_metrics_clean[feature_cols])

# UMAP dimensionality reduction
import umap
reducer = umap.UMAP(random_state=42)
X_umap = reducer.fit_transform(X_scaled)

# t-SNE dimensionality reduction
from sklearn.manifold import TSNE
tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
X_tsne = tsne.fit_transform(X_scaled)

# Clustering
import hdbscan
clusterer = hdbscan.HDBSCAN(min_cluster_size=5)
clusters = clusterer.fit_predict(X_scaled)

# Add to DataFrame
df_metrics_clean["cluster"] = clusters
df_metrics_clean["UMAP1"] = X_umap[:, 0]
df_metrics_clean["UMAP2"] = X_umap[:, 1]
df_metrics_clean["tSNE1"] = X_tsne[:, 0]
df_metrics_clean["tSNE2"] = X_tsne[:, 1]

print(df_metrics_clean.head())

Processing m/z features: 100%|██████████| 1000/1000 [23:43<00:00,  1.42s/it]
/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

/opt/anaconda3/lib/python3.12/site-packages/sklearn/manifold/_t_sne.py:1162: FutureWarning:

'n_iter' was renamed to 'max_iter' in version 1.5 and will be removed in 1.7.

         mz  moran_I_tissue  geary_C_tissue  entropy_tissue  cv_tissue  \
0  136.0150        0.415658        0.547822        8.402684   0.965441
1  136.0608        0.262929        0.729385        8.702899   0.630088
2  137.0251        0.549667        0.406121        8.616154   0.964382
3  138.0287        0.508409        0.452354        8.596314   0.921969
4  139.0359        0.363029        0.612376        8.537266   0.820836

   skew_tissue  region_size  moran_I_background  geary_C_background  \
0     3.751760         6199            0.493544            0.501015
1     2.034254         7144            0.494965            0.504816
2     7.986627         7151            0.721676            0.275891
3     5.827630         7122            0.701255            0.295633
4     3.310123         6636            0.650540            0.345992

   entropy_background  ...  has_H_adduct  has_Na_adduct  has_K_adduct  \
0            9.055275  ...             1              1             0
1            8.685133  ...             0              0             0
2            8.950049  ...             1              1             0
3            8.989311  ...             1              0             0
4            9.013560  ...             0              0             0

   has_Mplus1_isotope  has_Mplus2_isotope  cluster      UMAP1     UMAP2  \
0                   1                   1        7  -2.375989  1.969844
1                   0                   0        8  10.874235  5.166420
2                   1                   1        7  -3.225951  1.220740
3                   1                   0       -1   2.204940  0.031811
4                   0                   0        8  11.452809  4.569888

       tSNE1      tSNE2
0 -21.737032  -2.620142
1  33.821030  10.016300
2 -26.214365   2.943655
3 -24.446104  11.643754
4  35.291515  16.119926

[5 rows x 22 columns]

In [87]:
import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid", rc={"figure.figsize": (10, 8)})

# UMAP plot
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x="UMAP1", y="UMAP2",
    hue="cluster", palette="tab10",
    data=df_metrics_clean, s=50, linewidth=0, legend='full'
)
plt.title("UMAP Clustering of m/z Features")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

# t-SNE plot
plt.figure(figsize=(10, 8))
sns.scatterplot(
    x="tSNE1", y="tSNE2",
    hue="cluster", palette="tab10",
    data=df_metrics_clean, s=50, linewidth=0, legend='full'
)
plt.title("t-SNE Clustering of m/z Features")
plt.legend(title="Cluster", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

In [88]:
from sklearn.cluster import MiniBatchKMeans

# Choose number of clusters
n_clusters = 100  # or any number between 100-200

# Run clustering
kmeans = MiniBatchKMeans(n_clusters=n_clusters, random_state=42, batch_size=100)
df_metrics_clean["cluster"] = kmeans.fit_predict(X_scaled)

In [89]:
for cluster_id, group in df_metrics_clean.groupby("cluster"):
    print(f"\nCluster {cluster_id} ({len(group)} m/z features):")
    print(group["mz"].values)

Cluster 0 (9 m/z features):
[217.0514 218.056  261.0393 306.0433 397.0578 410.0475 425.0628 439.057
 603.5365]

Cluster 1 (21 m/z features):
[160.0107 318.0517 339.0374 366.0285 485.358  491.0306 513.0214 537.0208
 540.4258 553.9998 574.9745 631.0347 647.0388 667.0381 689.0372 711.0204
 713.001  729.0159 749.0038 775.098  791.0672]

Cluster 2 (6 m/z features):
[ 296.0663  497.3396  526.299   530.3032  534.2923 1495.1523]

Cluster 3 (21 m/z features):
[172.054  178.0269 184.072  197.1082 202.0613 202.1793 203.0369 215.0298
 240.0412 267.0272 305.0435 311.013  391.0428 594.0808 598.057  604.0622
 713.4442 724.5195 804.4848 804.5468 896.488 ]

Cluster 4 (14 m/z features):
[ 443.901   599.9377  821.5281  827.5714  849.5585  853.4827  869.4633
  872.556   875.4991  912.4556  963.4792  974.5565 1494.1565 1521.1633]

Cluster 5 (3 m/z features):
[604.5345 775.5356 825.5629]

Cluster 6 (15 m/z features):
[371.9835 460.0332 507.0164 511.0158 546.9926 547.9938 571.9841 681.0148
 682.0179 687.0215 701.0084 714.9844 723.0042 723.9907 918.9958]

Cluster 7 (6 m/z features):
[411.9507 560.0797 564.0651 567.9813 583.961  737.9794]

Cluster 8 (11 m/z features):
[315.0454 369.9904 381.0657 449.049  451.059  468.0562 485.0599 527.0004
 619.0599 621.0713 766.5276]

Cluster 9 (1 m/z features):
[836.6271]

Cluster 10 (14 m/z features):
[239.0343 254.0257 273.2634 304.0301 379.0653 380.0606 413.068  414.0625
 420.0367 580.9368 780.5778 786.4932 788.5027 812.5174]

Cluster 11 (7 m/z features):
[725.5188 764.6067 771.5526 785.5751 802.5665 822.5297 850.5641]

Cluster 12 (15 m/z features):
[308.0478 344.9885 404.9267 416.0729 426.0626 482.0163 508.0197 520.9935
 524.0176 541.9698 622.0728 638.0627 718.9828 777.5555 791.5339]

Cluster 13 (7 m/z features):
[199.9998 220.98   229.0025 356.9964 533.0012 662.0519 707.0211]

Cluster 14 (4 m/z features):
[276.0565 605.5548 746.58   789.6188]

Cluster 15 (2 m/z features):
[859.0277 861.0252]

Cluster 16 (38 m/z features):
[136.0608 163.0405 173.0578 179.0362 187.0399 191.0379 203.068  203.18
 214.0577 226.1111 243.0677 275.2736 277.0659 316.209  319.0414 341.3084
 350.0431 361.0668 385.0822 386.2827 387.0725 407.1967 435.059  440.403
 453.0549 457.0507 487.0621 518.326  535.09   551.0952 565.0818 595.0816
 599.4994 605.0714 609.0626 661.2994 751.3358 932.5598]

Cluster 17 (26 m/z features):
[220.0723 224.1    240.0953 257.2299 337.0706 339.0857 377.0703 405.1816
 433.0486 455.0366 481.0294 545.0745 547.0845 563.0803 577.0809 591.0623
 623.5002 649.5179 653.5411 723.4974 796.5415 802.4798 816.5298 832.515
 834.5319 948.5346]

Cluster 18 (11 m/z features):
[232.0653 353.0721 748.5259 757.5601 783.5694 793.5621 808.5768 814.5224
 815.532  830.5131 831.5201]

Cluster 19 (20 m/z features):
[136.015  199.0439 216.0426 316.0537 412.0659 424.0641 437.0375 440.0549
 445.0608 448.041  450.0488 488.0165 489.0298 509.0142 510.0096 575.0688
 597.0643 635.0444 657.0172 665.0323]

Cluster 20 (6 m/z features):
[192.9801 284.0206 346.0029 364.0014 383.9606 500.0308]

Cluster 21 (3 m/z features):
[230.9492 252.9273 268.8998]

Cluster 22 (10 m/z features):
[375.0044 523.0186 528.0132 529.017  543.9945 544.9929 548.996  550.0092
 720.0018 721.0097]

Cluster 23 (11 m/z features):
[229.0488 257.0478 258.0498 339.2947 354.3367 367.3328 368.3461 369.3523
 370.3516 620.6035 630.6179]

Cluster 24 (20 m/z features):
[ 597.9289  598.9329  772.5231  773.5307  798.5391  799.5511  800.5515
  820.5273  824.5594  826.5668  828.5011  832.5781  844.5262  845.529
  846.5322  847.5362  848.5533  852.4881  868.4722 1520.1588]

Cluster 25 (12 m/z features):
[362.9775 392.9619 451.161  473.1425 562.9767 568.9807 588.9623 738.9761
 743.9934 744.9822 759.9656 934.9747]

Cluster 26 (6 m/z features):
[361.0087 376.0027 376.9855 531.0173 552.0181 693.0084]

Cluster 27 (15 m/z features):
[181.0163 222.0783 233.0774 266.072  280.0902 310.0742 321.0332 470.0609
 473.038  623.0859 797.577  805.5502 837.5366 858.5287 925.5197]

Cluster 28 (1 m/z features):
[357.987]

Cluster 29 (2 m/z features):
[332.3338 551.0132]

Cluster 30 (17 m/z features):
[154.0255 196.9856 308.1168 372.9863 504.0026 506.0141 659.0333 663.0409
 675.012  678.0215 679.0223 684.0262 685.0201 686.0261 696.9911 700.003
 703.0097]

Cluster 31 (15 m/z features):
[ 856.0102  857.0198  876.0159  877.0113  888.9867  889.9894  894.9983
  898.0182  901.004   917.9902 1051.0231 1065.9956 1071.0052 1072.0057
 1073.021 ]

Cluster 32 (3 m/z features):
[587.9561 757.9567 912.9832]

Cluster 33 (17 m/z features):
[139.0359 258.113  270.1184 328.3184 355.0768 361.2742 367.0818 389.3006
 466.3291 502.2887 564.2518 733.5854 790.6252 794.5587 812.592  835.6044
 950.9432]

Cluster 34 (7 m/z features):
[ 645.0522  837.0439  841.0405  853.0236  863.0378 1033.0245 1057.0334]

Cluster 35 (11 m/z features):
[822.6423 838.6237 839.6229 848.6424 849.6475 850.6533 851.6469 852.6411
 864.6292 865.6309 866.646 ]

Cluster 36 (17 m/z features):
[354.008  373.9904 530.0217 660.0424 661.0524 676.022  683.0331 698.0059
 699.0099 704.0173 705.0255 706.0229 713.9808 725.0014 726.0129 875.0211
 896.0043]

Cluster 37 (9 m/z features):
[365.97   459.0317 525.9985 620.0598 636.0461 658.0248 664.0419 680.0125
 702.0029]

Cluster 38 (7 m/z features):
[286.0403 317.048  469.058  486.0605 702.5467 753.5875 834.595 ]

Cluster 39 (18 m/z features):
[185.0686 278.0479 311.1516 325.004  333.1222 334.1111 351.1385 409.1727
 445.1529 487.1585 582.253  640.3147 655.0489 655.3171 677.2827 790.3306
 814.3231 882.5672]

Cluster 40 (2 m/z features):
[835.0365 851.0099]

Cluster 41 (5 m/z features):
[ 899.0129  916.985  1077.0151 1078.0327 1093.9899]

Cluster 42 (10 m/z features):
[446.0654 490.0345 537.9825 666.0349 688.0289 691.9973 715.9888 717.9764
 813.3141 890.9927]

Cluster 43 (21 m/z features):
[176.0111 245.0458 262.0491 263.0537 264.0603 289.0389 291.0466 292.0531
 312.0225 313.0337 314.0387 329.0229 382.0721 383.0799 398.0677 399.0702
 427.0635 467.0459 637.0596 728.5562 788.613 ]

Cluster 44 (18 m/z features):
[259.0608 264.2661 356.3532 398.3291 562.3243 587.5433 606.5544 621.6046
 631.6271 634.6154 646.6168 648.6279 730.5729 732.6042 782.653  792.6645
 810.6888 832.6662]

Cluster 45 (5 m/z features):
[270.0538 279.0389 371.0661 429.069  639.0779]

Cluster 46 (1 m/z features):
[346.0598]

Cluster 47 (5 m/z features):
[808.6637 823.632  840.6227 853.6358 867.6489]

Cluster 48 (14 m/z features):
[200.0492 201.0571 241.0502 268.0413 296.0287 340.3089 353.3347 365.0685
 394.0619 415.0671 421.0485 422.0525 593.0809 603.0646]

Cluster 49 (11 m/z features):
[195.0905 199.0008 260.0386 269.0502 285.0295 307.1212 309.137  355.0027
 370.982  461.0358 659.2911]

Cluster 50 (6 m/z features):
[ 348.0689  805.4882  824.4467  850.4877  866.4661 1542.1475]

Cluster 51 (3 m/z features):
[210.9897 348.0119 538.9855]

Cluster 52 (18 m/z features):
[213.056  248.0624 355.3483 366.0703 384.0804 384.3286 385.2707 385.3478
 395.068  397.3363 427.9302 441.063  496.3372 548.5356 578.5188 652.537
 774.5268 784.572 ]

Cluster 53 (7 m/z features):
[ 858.0298  874.014   878.0072  879.0167  902.0134 1050.0183 1056.0259]

Cluster 54 (6 m/z features):
[231.9456 232.9441 251.9214 267.8913 422.932  444.9043]

Cluster 55 (4 m/z features):
[ 880.0137  881.0243  882.0225 1055.0187]

Cluster 56 (11 m/z features):
[137.0251 228.0455 244.0353 246.0516 247.0594 272.0306 273.0397 274.0435
 275.0563 288.0302 290.0419]

Cluster 57 (11 m/z features):
[180.0717 309.0449 401.0788 629.5439 736.5804 742.5174 744.5532 747.5825
 752.557  754.5827 778.5663]

Cluster 58 (10 m/z features):
[242.0613 628.5364 751.5392 767.5312 769.5648 770.5583 790.527  801.5524
 806.5172 807.5094]

Cluster 59 (7 m/z features):
[282.2793 326.304  396.31   464.3135 480.3211 522.3597 560.3174]

Cluster 60 (6 m/z features):
[294.0637 316.1003 332.095  341.0906 581.084  653.0389]

Cluster 61 (12 m/z features):
[213.9619 249.0743 265.0616 279.0973 363.0524 452.061  559.0778 781.5784
 787.4854 813.5133 833.5862 836.5261]

Cluster 62 (6 m/z features):
[483.033  729.5701 731.6    735.5735 763.6049 811.5966]

Cluster 63 (29 m/z features):
[161.1338 203.2236 215.1771 243.2107 247.2447 255.2101 256.0827 259.2436
 264.1099 283.0942 284.0794 284.2929 299.0563 303.2312 313.2732 327.2354
 371.3606 386.3513 482.3231 508.2855 549.5485 551.5052 579.5273 611.5435
 635.5397 655.563  718.538  720.5643 741.4946]

Cluster 64 (3 m/z features):
[471.0364 641.0331 709.0077]

Cluster 65 (1 m/z features):
[347.0108]

Cluster 66 (23 m/z features):
[198.121  222.0327 242.1088 250.0883 269.1003 366.1371 697.4753 714.4474
 762.4953 778.4689 789.4961 808.5023 818.5523 826.4664 854.4907 856.5085
 876.5071 897.4819 926.5427 950.5529 958.5659 964.496  975.5518]

Cluster 67 (6 m/z features):
[287.0455 449.3544 524.3675 554.2875 650.4418 703.5655]

Cluster 68 (1 m/z features):
[352.3177]

Cluster 69 (5 m/z features):
[298.0454 347.0677 354.0737 576.0744 626.5129]

Cluster 70 (5 m/z features):
[ 872.9946  920.0021 1067.0081 1074.0223 1095.0011]

Cluster 71 (17 m/z features):
[229.9417 307.0371 369.0587 442.063  443.0551 444.0666 466.0368 499.0256
 542.9766 749.5297 759.5684 765.5245 782.5675 787.5956 809.5828 829.5068
 874.5046]

Cluster 72 (6 m/z features):
[ 201.9372  423.9832  664.1207  790.9199  966.9248 1522.1682]

Cluster 73 (3 m/z features):
[716.9822 834.2923 900.0081]

Cluster 74 (7 m/z features):
[235.9458 328.002  384.9708 391.9758 408.9519 412.9616 424.9368]

Cluster 75 (3 m/z features):
[763.967  884.0076 924.0059]

Cluster 76 (18 m/z features):
[165.02   350.0839 386.0081 386.9952 387.1928 392.0363 408.0254 413.2633
 428.0476 465.1795 477.0158 489.1071 503.0424 584.9532 599.3925 752.9524
 837.6503 966.5311]

Cluster 77 (13 m/z features):
[138.0287 159.007  189.0757 196.0981 274.2748 297.0362 349.039  370.0575
 581.2419 639.3097 660.2892 676.2717 758.9668]

Cluster 78 (16 m/z features):
[ 869.0128  883.0213  891.9965  913.9861  920.9955  940.9789 1039.0396
 1052.0283 1068.0066 1075.01   1080.0408 1088.9844 1095.9983 1249.03
 1255.0399 1271.0072]

Cluster 79 (8 m/z features):
[155.035  177.0146 219.063  293.0538 310.1357 400.0739 405.0673 502.0343]

Cluster 80 (3 m/z features):
[197.9919 501.0369 505.0127]

Cluster 81 (10 m/z features):
[397.9893 573.9908 764.9689 807.038  813.0526 829.029  836.2988 885.0075
 905.032  925.0016]

Cluster 82 (13 m/z features):
[349.994  350.9995 388.9561 389.9643 405.9378 438.0421 484.0411 558.954
 559.9661 560.9688 561.9723 735.9644 911.9808]

Cluster 83 (12 m/z features):
[423.0667 465.0382 734.5673 750.5461 760.5916 761.5914 762.5918 768.5477
 776.5574 786.6035 792.5538 810.6019]

Cluster 84 (14 m/z features):
[330.0215 331.0297 332.0313 333.0266 334.0233 335.0136 352.0063 353.0146
 367.9774 368.9916 522.0106 546.0025 637.302  638.3054]

Cluster 85 (10 m/z features):
[219.9751 395.9797 396.9882 553.0034 677.0327 722.0066 727.025  728.026
 897.011  903.0234]

Cluster 86 (12 m/z features):
[ 273.2201  600.9327  614.9061  710.485   739.4628  774.94    828.5639
  840.4328  870.4678  873.5623  913.4582 1544.1542]

Cluster 87 (1 m/z features):
[734.9579]

Cluster 88 (23 m/z features):
[211.0595 301.0227 331.117  335.0695 396.0666 407.0558 449.1508 463.0443
 463.1664 517.0743 531.0776 533.0819 549.088  557.0665 561.0825 579.086
 585.0588 587.0671 589.0684 601.0612 607.0599 617.0518 773.0815]

Cluster 89 (2 m/z features):
[361.9717 742.9933]

Cluster 90 (8 m/z features):
[364.0681 564.9677 565.9747 566.9828 581.9474 736.9716 740.9714 741.9821]

Cluster 91 (8 m/z features):
[402.0237 402.9348 464.0783 542.0715 580.032  602.0143 617.9849 702.0723]

Cluster 92 (1 m/z features):
[643.0466]

Cluster 93 (11 m/z features):
[227.0378 230.0543 243.0269 255.0287 256.0338 271.0377 295.0229 393.0658
 409.0579 411.065  675.2615]

Cluster 94 (6 m/z features):
[302.0159 366.9731 390.9737 406.9501 407.9548 582.959 ]

Cluster 95 (12 m/z features):
[ 336.0213  355.9988  360.0056  462.0395  512.0132  532.0038  572.9871
  708.0082  747.9885  835.3016  904.034  1079.0364]

Cluster 96 (2 m/z features):
[214.9722 428.9334]

Cluster 97 (13 m/z features):
[231.0686 268.1057 365.3188 366.3293 383.3277 577.5215 625.5188 627.5297
 651.5335 740.4961 756.551  758.5699 764.5222]

Cluster 98 (16 m/z features):
[156.0424 190.0676 204.0398 233.0507 251.0421 337.0225 342.3255 357.0624
 406.0697 417.071  447.0619 498.002  519.0818 525.0175 599.0718 615.0577]

Cluster 99 (2 m/z features):
[303.0184 365.0184]

In [90]:
clustered_mzs = df_metrics_clean.groupby("cluster")["mz"].apply(list).to_dict()

In [91]:
df_metrics_clean[["mz", "cluster"]].sort_values("cluster").to_csv("clustered_mzs.csv", index=False)

In [92]:
cluster_counts = df_metrics_clean["cluster"].value_counts().sort_index()
print(cluster_counts)

cluster
0      9
1     21
2      6
3     21
4     14
      ..
95    12
96     2
97    13
98    16
99     2
Name: count, Length: 100, dtype: int64

In [93]:
import os
import plotly.io as pio

# Ensure the image folder exists
os.makedirs(f"images_from_clusters_adducts", exist_ok=True)

# Merge cluster info with AnnData's m/z values
mz_cluster_map = dict(zip(df_metrics_clean["mz"].astype(float), df_metrics_clean["cluster"]))

# Compute the global spectrum
global_spectrum = adata.X.sum(axis=0).A1 if hasattr(adata.X, "A1") else np.asarray(adata.X.sum(axis=0)).flatten()

# Get indices of m/z values sorted by intensity (descending)
sorted_indices = np.argsort(global_spectrum)[::-1]

# Select indices of interest (e.g., all, top N, etc.)
selected_indices = sorted_indices[0:]  # You can limit with [10:20] if desired

# Get corresponding m/z values from adata.var
selected_mz = adata.var["mzs"].values[selected_indices].astype(float)

# Generate and save images
for mz in selected_mz:
    if mz not in mz_cluster_map:
        print(f"Skipping m/z {mz:.4f} — not in clustered data.")
        continue

    cluster_id = mz_cluster_map[mz]
    fig = plot_mz_across_sample_custom_tic(adata, mz, tol=0.001)  # Make sure this function returns a Plotly fig

    filename = f"images_from_clusters_adducts/cluster_{cluster_id}_mz_{mz:.4f}_.png"
    pio.write_image(fig, filename)
    print(f"Saved: {filename}")

Saved: images_from_clusters_adducts/cluster_56_mz_273.0397_.png
Saved: images_from_clusters_adducts/cluster_56_mz_137.0251_.png
Saved: images_from_clusters_adducts/cluster_56_mz_274.0435_.png
Saved: images_from_clusters_adducts/cluster_23_mz_369.3523_.png
Saved: images_from_clusters_adducts/cluster_84_mz_331.0297_.png
Saved: images_from_clusters_adducts/cluster_23_mz_257.0478_.png
Saved: images_from_clusters_adducts/cluster_49_mz_195.0905_.png
Saved: images_from_clusters_adducts/cluster_84_mz_637.3020_.png
Saved: images_from_clusters_adducts/cluster_43_mz_313.0337_.png
Saved: images_from_clusters_adducts/cluster_56_mz_275.0563_.png
Saved: images_from_clusters_adducts/cluster_43_mz_245.0458_.png
Saved: images_from_clusters_adducts/cluster_84_mz_333.0266_.png
Saved: images_from_clusters_adducts/cluster_80_mz_197.9919_.png
Saved: images_from_clusters_adducts/cluster_56_mz_244.0353_.png
Saved: images_from_clusters_adducts/cluster_56_mz_246.0516_.png
Saved: images_from_clusters_adducts/cluster_83_mz_734.5673_.png
Saved: images_from_clusters_adducts/cluster_84_mz_330.0215_.png
Saved: images_from_clusters_adducts/cluster_65_mz_347.0108_.png
Saved: images_from_clusters_adducts/cluster_29_mz_551.0132_.png
Saved: images_from_clusters_adducts/cluster_23_mz_258.0498_.png
Saved: images_from_clusters_adducts/cluster_23_mz_229.0488_.png
Saved: images_from_clusters_adducts/cluster_80_mz_501.0369_.png
Saved: images_from_clusters_adducts/cluster_49_mz_199.0008_.png
Saved: images_from_clusters_adducts/cluster_84_mz_332.0313_.png
Saved: images_from_clusters_adducts/cluster_22_mz_544.9929_.png
Saved: images_from_clusters_adducts/cluster_24_mz_798.5391_.png
Saved: images_from_clusters_adducts/cluster_22_mz_375.0044_.png
Saved: images_from_clusters_adducts/cluster_56_mz_290.0419_.png
Saved: images_from_clusters_adducts/cluster_23_mz_370.3516_.png
Saved: images_from_clusters_adducts/cluster_43_mz_291.0466_.png
Saved: images_from_clusters_adducts/cluster_84_mz_638.3054_.png
Saved: images_from_clusters_adducts/cluster_3_mz_184.0720_.png
Saved: images_from_clusters_adducts/cluster_20_mz_346.0029_.png
Saved: images_from_clusters_adducts/cluster_83_mz_760.5916_.png
Saved: images_from_clusters_adducts/cluster_84_mz_368.9916_.png
Saved: images_from_clusters_adducts/cluster_22_mz_721.0097_.png
Saved: images_from_clusters_adducts/cluster_93_mz_409.0579_.png
Saved: images_from_clusters_adducts/cluster_84_mz_367.9774_.png
Saved: images_from_clusters_adducts/cluster_49_mz_309.1370_.png
Saved: images_from_clusters_adducts/cluster_22_mz_543.9945_.png
Saved: images_from_clusters_adducts/cluster_49_mz_285.0295_.png
Saved: images_from_clusters_adducts/cluster_77_mz_138.0287_.png
Saved: images_from_clusters_adducts/cluster_43_mz_262.0491_.png
Saved: images_from_clusters_adducts/cluster_22_mz_550.0092_.png
Saved: images_from_clusters_adducts/cluster_49_mz_307.1212_.png
Saved: images_from_clusters_adducts/cluster_77_mz_159.0070_.png
Saved: images_from_clusters_adducts/cluster_24_mz_772.5231_.png
Saved: images_from_clusters_adducts/cluster_56_mz_247.0594_.png
Saved: images_from_clusters_adducts/cluster_62_mz_735.5735_.png
Saved: images_from_clusters_adducts/cluster_49_mz_659.2911_.png
Saved: images_from_clusters_adducts/cluster_56_mz_272.0306_.png
Saved: images_from_clusters_adducts/cluster_8_mz_485.0599_.png
Saved: images_from_clusters_adducts/cluster_43_mz_467.0459_.png
Saved: images_from_clusters_adducts/cluster_8_mz_315.0454_.png
Saved: images_from_clusters_adducts/cluster_84_mz_335.0136_.png
Saved: images_from_clusters_adducts/cluster_84_mz_353.0146_.png
Saved: images_from_clusters_adducts/cluster_22_mz_523.0186_.png
Saved: images_from_clusters_adducts/cluster_77_mz_297.0362_.png
Saved: images_from_clusters_adducts/cluster_49_mz_269.0502_.png
Saved: images_from_clusters_adducts/cluster_62_mz_483.0330_.png
Saved: images_from_clusters_adducts/cluster_56_mz_228.0455_.png
Saved: images_from_clusters_adducts/cluster_93_mz_256.0338_.png
Saved: images_from_clusters_adducts/cluster_85_mz_727.0250_.png
Saved: images_from_clusters_adducts/cluster_43_mz_329.0229_.png
Saved: images_from_clusters_adducts/cluster_43_mz_289.0389_.png
Saved: images_from_clusters_adducts/cluster_23_mz_367.3328_.png
Saved: images_from_clusters_adducts/cluster_77_mz_196.0981_.png
Saved: images_from_clusters_adducts/cluster_43_mz_314.0387_.png
Saved: images_from_clusters_adducts/cluster_89_mz_361.9717_.png
Saved: images_from_clusters_adducts/cluster_84_mz_352.0063_.png
Saved: images_from_clusters_adducts/cluster_0_mz_218.0560_.png
Saved: images_from_clusters_adducts/cluster_14_mz_276.0565_.png
Saved: images_from_clusters_adducts/cluster_85_mz_219.9751_.png
Saved: images_from_clusters_adducts/cluster_22_mz_529.0170_.png
Saved: images_from_clusters_adducts/cluster_43_mz_292.0531_.png
Saved: images_from_clusters_adducts/cluster_97_mz_231.0686_.png
Saved: images_from_clusters_adducts/cluster_97_mz_651.5335_.png
Saved: images_from_clusters_adducts/cluster_22_mz_720.0018_.png
Saved: images_from_clusters_adducts/cluster_49_mz_355.0027_.png
Saved: images_from_clusters_adducts/cluster_67_mz_287.0455_.png
Saved: images_from_clusters_adducts/cluster_50_mz_348.0689_.png
Saved: images_from_clusters_adducts/cluster_24_mz_799.5511_.png
Saved: images_from_clusters_adducts/cluster_71_mz_782.5675_.png
Saved: images_from_clusters_adducts/cluster_97_mz_756.5510_.png
Saved: images_from_clusters_adducts/cluster_44_mz_259.0608_.png
Saved: images_from_clusters_adducts/cluster_90_mz_566.9828_.png
Saved: images_from_clusters_adducts/cluster_22_mz_548.9960_.png
Saved: images_from_clusters_adducts/cluster_93_mz_295.0229_.png
Saved: images_from_clusters_adducts/cluster_93_mz_255.0287_.png
Saved: images_from_clusters_adducts/cluster_21_mz_230.9492_.png
Saved: images_from_clusters_adducts/cluster_83_mz_761.5914_.png
Saved: images_from_clusters_adducts/cluster_8_mz_449.0490_.png
Saved: images_from_clusters_adducts/cluster_62_mz_731.6000_.png
Saved: images_from_clusters_adducts/cluster_43_mz_176.0111_.png
Saved: images_from_clusters_adducts/cluster_84_mz_334.0233_.png
Saved: images_from_clusters_adducts/cluster_22_mz_528.0132_.png
Saved: images_from_clusters_adducts/cluster_36_mz_705.0255_.png
Saved: images_from_clusters_adducts/cluster_97_mz_627.5297_.png
Saved: images_from_clusters_adducts/cluster_26_mz_552.0181_.png
Saved: images_from_clusters_adducts/cluster_79_mz_177.0146_.png
Saved: images_from_clusters_adducts/cluster_20_mz_500.0308_.png
Saved: images_from_clusters_adducts/cluster_51_mz_348.0119_.png
Saved: images_from_clusters_adducts/cluster_56_mz_288.0302_.png
Saved: images_from_clusters_adducts/cluster_23_mz_368.3461_.png
Saved: images_from_clusters_adducts/cluster_49_mz_370.9820_.png
Saved: images_from_clusters_adducts/cluster_77_mz_189.0757_.png
Saved: images_from_clusters_adducts/cluster_79_mz_502.0343_.png
Saved: images_from_clusters_adducts/cluster_84_mz_546.0025_.png
Saved: images_from_clusters_adducts/cluster_77_mz_349.0390_.png
Saved: images_from_clusters_adducts/cluster_85_mz_396.9882_.png
Saved: images_from_clusters_adducts/cluster_94_mz_366.9731_.png
Saved: images_from_clusters_adducts/cluster_99_mz_303.0184_.png
Saved: images_from_clusters_adducts/cluster_24_mz_800.5515_.png
Saved: images_from_clusters_adducts/cluster_43_mz_264.0603_.png
Saved: images_from_clusters_adducts/cluster_24_mz_773.5307_.png
Saved: images_from_clusters_adducts/cluster_0_mz_261.0393_.png
Saved: images_from_clusters_adducts/cluster_82_mz_350.9995_.png
Saved: images_from_clusters_adducts/cluster_93_mz_271.0377_.png
Saved: images_from_clusters_adducts/cluster_93_mz_230.0543_.png
Saved: images_from_clusters_adducts/cluster_43_mz_312.0225_.png
Saved: images_from_clusters_adducts/cluster_85_mz_722.0066_.png
Saved: images_from_clusters_adducts/cluster_43_mz_263.0537_.png
Saved: images_from_clusters_adducts/cluster_58_mz_769.5648_.png
Saved: images_from_clusters_adducts/cluster_71_mz_542.9766_.png
Saved: images_from_clusters_adducts/cluster_26_mz_376.9855_.png
Saved: images_from_clusters_adducts/cluster_97_mz_268.1057_.png
Saved: images_from_clusters_adducts/cluster_93_mz_411.0650_.png
Saved: images_from_clusters_adducts/cluster_94_mz_390.9737_.png
Saved: images_from_clusters_adducts/cluster_36_mz_373.9904_.png
Saved: images_from_clusters_adducts/cluster_93_mz_675.2615_.png
Saved: images_from_clusters_adducts/cluster_38_mz_286.0403_.png
Saved: images_from_clusters_adducts/cluster_38_mz_317.0480_.png
Saved: images_from_clusters_adducts/cluster_49_mz_461.0358_.png
Saved: images_from_clusters_adducts/cluster_43_mz_637.0596_.png
Saved: images_from_clusters_adducts/cluster_8_mz_381.0657_.png
Saved: images_from_clusters_adducts/cluster_85_mz_395.9797_.png
Saved: images_from_clusters_adducts/cluster_89_mz_742.9933_.png
Saved: images_from_clusters_adducts/cluster_80_mz_505.0127_.png
Saved: images_from_clusters_adducts/cluster_8_mz_468.0562_.png
Saved: images_from_clusters_adducts/cluster_57_mz_180.0717_.png
Saved: images_from_clusters_adducts/cluster_77_mz_639.3097_.png
Saved: images_from_clusters_adducts/cluster_43_mz_427.0635_.png
Saved: images_from_clusters_adducts/cluster_77_mz_660.2892_.png
Saved: images_from_clusters_adducts/cluster_52_mz_213.0560_.png
Saved: images_from_clusters_adducts/cluster_20_mz_192.9801_.png
Saved: images_from_clusters_adducts/cluster_0_mz_439.0570_.png
Saved: images_from_clusters_adducts/cluster_38_mz_753.5875_.png
Saved: images_from_clusters_adducts/cluster_38_mz_469.0580_.png
Saved: images_from_clusters_adducts/cluster_94_mz_406.9501_.png
Saved: images_from_clusters_adducts/cluster_97_mz_577.5215_.png
Saved: images_from_clusters_adducts/cluster_24_mz_826.5668_.png
Saved: images_from_clusters_adducts/cluster_43_mz_383.0799_.png
Saved: images_from_clusters_adducts/cluster_30_mz_372.9863_.png
Saved: images_from_clusters_adducts/cluster_36_mz_661.0524_.png
Saved: images_from_clusters_adducts/cluster_0_mz_217.0514_.png
Saved: images_from_clusters_adducts/cluster_36_mz_354.0080_.png
Saved: images_from_clusters_adducts/cluster_77_mz_274.2748_.png
Saved: images_from_clusters_adducts/cluster_38_mz_486.0605_.png
Saved: images_from_clusters_adducts/cluster_0_mz_306.0433_.png
Saved: images_from_clusters_adducts/cluster_94_mz_582.9590_.png
Saved: images_from_clusters_adducts/cluster_93_mz_227.0378_.png
Saved: images_from_clusters_adducts/cluster_36_mz_726.0129_.png
Saved: images_from_clusters_adducts/cluster_82_mz_484.0411_.png
Saved: images_from_clusters_adducts/cluster_48_mz_201.0571_.png
Saved: images_from_clusters_adducts/cluster_43_mz_382.0721_.png
Saved: images_from_clusters_adducts/cluster_43_mz_788.6130_.png
Saved: images_from_clusters_adducts/cluster_24_mz_598.9329_.png
Saved: images_from_clusters_adducts/cluster_54_mz_422.9320_.png
Saved: images_from_clusters_adducts/cluster_83_mz_762.5918_.png
Saved: images_from_clusters_adducts/cluster_14_mz_605.5548_.png
Saved: images_from_clusters_adducts/cluster_52_mz_652.5370_.png
Saved: images_from_clusters_adducts/cluster_2_mz_296.0663_.png
Saved: images_from_clusters_adducts/cluster_84_mz_522.0106_.png
Saved: images_from_clusters_adducts/cluster_0_mz_410.0475_.png
Saved: images_from_clusters_adducts/cluster_36_mz_530.0217_.png
Saved: images_from_clusters_adducts/cluster_26_mz_361.0087_.png
Saved: images_from_clusters_adducts/cluster_48_mz_421.0485_.png
Saved: images_from_clusters_adducts/cluster_36_mz_704.0173_.png
Saved: images_from_clusters_adducts/cluster_48_mz_268.0413_.png
Saved: images_from_clusters_adducts/cluster_71_mz_229.9417_.png
Saved: images_from_clusters_adducts/cluster_8_mz_527.0004_.png
Saved: images_from_clusters_adducts/cluster_8_mz_621.0713_.png
Saved: images_from_clusters_adducts/cluster_83_mz_465.0382_.png
Saved: images_from_clusters_adducts/cluster_6_mz_511.0158_.png
Saved: images_from_clusters_adducts/cluster_25_mz_362.9775_.png
Saved: images_from_clusters_adducts/cluster_52_mz_496.3372_.png
Saved: images_from_clusters_adducts/cluster_86_mz_739.4628_.png
Saved: images_from_clusters_adducts/cluster_6_mz_571.9841_.png
Saved: images_from_clusters_adducts/cluster_52_mz_385.3478_.png
Saved: images_from_clusters_adducts/cluster_36_mz_699.0099_.png
Saved: images_from_clusters_adducts/cluster_90_mz_565.9747_.png
Saved: images_from_clusters_adducts/cluster_93_mz_243.0269_.png
Saved: images_from_clusters_adducts/cluster_30_mz_196.9856_.png
Saved: images_from_clusters_adducts/cluster_85_mz_728.0260_.png
Saved: images_from_clusters_adducts/cluster_99_mz_365.0184_.png
Saved: images_from_clusters_adducts/cluster_20_mz_284.0206_.png
Saved: images_from_clusters_adducts/cluster_12_mz_718.9828_.png
Saved: images_from_clusters_adducts/cluster_8_mz_369.9904_.png
Saved: images_from_clusters_adducts/cluster_8_mz_451.0590_.png
Saved: images_from_clusters_adducts/cluster_71_mz_466.0368_.png
Saved: images_from_clusters_adducts/cluster_36_mz_725.0014_.png
Saved: images_from_clusters_adducts/cluster_90_mz_736.9716_.png
Saved: images_from_clusters_adducts/cluster_49_mz_260.0386_.png
Saved: images_from_clusters_adducts/cluster_48_mz_365.0685_.png
Saved: images_from_clusters_adducts/cluster_45_mz_270.0538_.png
Saved: images_from_clusters_adducts/cluster_76_mz_428.0476_.png
Saved: images_from_clusters_adducts/cluster_26_mz_376.0027_.png
Saved: images_from_clusters_adducts/cluster_12_mz_308.0478_.png
Saved: images_from_clusters_adducts/cluster_52_mz_248.0624_.png
Saved: images_from_clusters_adducts/cluster_93_mz_393.0658_.png
Saved: images_from_clusters_adducts/cluster_83_mz_810.6019_.png
Saved: images_from_clusters_adducts/cluster_36_mz_706.0229_.png
Saved: images_from_clusters_adducts/cluster_18_mz_783.5694_.png
Saved: images_from_clusters_adducts/cluster_44_mz_732.6042_.png
Saved: images_from_clusters_adducts/cluster_17_mz_240.0953_.png
Saved: images_from_clusters_adducts/cluster_71_mz_307.0371_.png
Saved: images_from_clusters_adducts/cluster_82_mz_560.9688_.png
Saved: images_from_clusters_adducts/cluster_33_mz_139.0359_.png
Saved: images_from_clusters_adducts/cluster_12_mz_524.0176_.png
Saved: images_from_clusters_adducts/cluster_83_mz_423.0667_.png
Saved: images_from_clusters_adducts/cluster_36_mz_683.0331_.png
Saved: images_from_clusters_adducts/cluster_6_mz_687.0215_.png
Saved: images_from_clusters_adducts/cluster_19_mz_136.0150_.png
Saved: images_from_clusters_adducts/cluster_44_mz_264.2661_.png
Saved: images_from_clusters_adducts/cluster_25_mz_451.1610_.png
Saved: images_from_clusters_adducts/cluster_12_mz_482.0163_.png
Saved: images_from_clusters_adducts/cluster_79_mz_293.0538_.png
Saved: images_from_clusters_adducts/cluster_23_mz_354.3367_.png
Saved: images_from_clusters_adducts/cluster_6_mz_681.0148_.png
Saved: images_from_clusters_adducts/cluster_57_mz_736.5804_.png
Saved: images_from_clusters_adducts/cluster_71_mz_499.0256_.png
Saved: images_from_clusters_adducts/cluster_79_mz_310.1357_.png
Saved: images_from_clusters_adducts/cluster_23_mz_339.2947_.png
Saved: images_from_clusters_adducts/cluster_30_mz_703.0097_.png
Saved: images_from_clusters_adducts/cluster_30_mz_154.0255_.png
Saved: images_from_clusters_adducts/cluster_77_mz_581.2419_.png
Saved: images_from_clusters_adducts/cluster_3_mz_197.1082_.png
Saved: images_from_clusters_adducts/cluster_19_mz_316.0537_.png
Saved: images_from_clusters_adducts/cluster_43_mz_399.0702_.png
Saved: images_from_clusters_adducts/cluster_85_mz_553.0034_.png
Saved: images_from_clusters_adducts/cluster_3_mz_311.0130_.png
Saved: images_from_clusters_adducts/cluster_85_mz_677.0327_.png
Saved: images_from_clusters_adducts/cluster_13_mz_356.9964_.png
Saved: images_from_clusters_adducts/cluster_79_mz_155.0350_.png
Saved: images_from_clusters_adducts/cluster_3_mz_713.4442_.png
Saved: images_from_clusters_adducts/cluster_30_mz_308.1168_.png
Saved: images_from_clusters_adducts/cluster_0_mz_425.0628_.png
Saved: images_from_clusters_adducts/cluster_58_mz_628.5364_.png
Saved: images_from_clusters_adducts/cluster_52_mz_385.2707_.png
Saved: images_from_clusters_adducts/cluster_63_mz_371.3606_.png
Saved: images_from_clusters_adducts/cluster_44_mz_356.3532_.png
Saved: images_from_clusters_adducts/cluster_30_mz_659.0333_.png
Saved: images_from_clusters_adducts/cluster_36_mz_660.0424_.png
Saved: images_from_clusters_adducts/cluster_30_mz_663.0409_.png
Saved: images_from_clusters_adducts/cluster_48_mz_241.0502_.png
Saved: images_from_clusters_adducts/cluster_79_mz_219.0630_.png
Saved: images_from_clusters_adducts/cluster_96_mz_214.9722_.png
Saved: images_from_clusters_adducts/cluster_95_mz_336.0213_.png
Saved: images_from_clusters_adducts/cluster_52_mz_441.0630_.png
Saved: images_from_clusters_adducts/cluster_3_mz_305.0435_.png
Saved: images_from_clusters_adducts/cluster_95_mz_572.9871_.png
Saved: images_from_clusters_adducts/cluster_3_mz_178.0269_.png
Saved: images_from_clusters_adducts/cluster_36_mz_698.0059_.png
Saved: images_from_clusters_adducts/cluster_12_mz_520.9935_.png
Saved: images_from_clusters_adducts/cluster_16_mz_487.0621_.png
Saved: images_from_clusters_adducts/cluster_83_mz_768.5477_.png
Saved: images_from_clusters_adducts/cluster_48_mz_296.0287_.png
Saved: images_from_clusters_adducts/cluster_83_mz_792.5538_.png
Saved: images_from_clusters_adducts/cluster_76_mz_387.1928_.png
Saved: images_from_clusters_adducts/cluster_13_mz_662.0519_.png
Saved: images_from_clusters_adducts/cluster_6_mz_723.0042_.png
Saved: images_from_clusters_adducts/cluster_8_mz_619.0599_.png
Saved: images_from_clusters_adducts/cluster_23_mz_630.6179_.png
Saved: images_from_clusters_adducts/cluster_52_mz_774.5268_.png
Saved: images_from_clusters_adducts/cluster_19_mz_489.0298_.png
Saved: images_from_clusters_adducts/cluster_6_mz_507.0164_.png
Saved: images_from_clusters_adducts/cluster_58_mz_242.0613_.png
Saved: images_from_clusters_adducts/cluster_76_mz_386.9952_.png
Saved: images_from_clusters_adducts/cluster_30_mz_504.0026_.png
Saved: images_from_clusters_adducts/cluster_44_mz_398.3291_.png
Saved: images_from_clusters_adducts/cluster_43_mz_398.0677_.png
Saved: images_from_clusters_adducts/cluster_6_mz_682.0179_.png
Saved: images_from_clusters_adducts/cluster_13_mz_220.9800_.png
Saved: images_from_clusters_adducts/cluster_6_mz_714.9844_.png
Saved: images_from_clusters_adducts/cluster_79_mz_400.0739_.png
Saved: images_from_clusters_adducts/cluster_13_mz_707.0211_.png
Saved: images_from_clusters_adducts/cluster_6_mz_546.9926_.png
Saved: images_from_clusters_adducts/cluster_17_mz_224.1000_.png
Saved: images_from_clusters_adducts/cluster_79_mz_405.0673_.png
Saved: images_from_clusters_adducts/cluster_16_mz_341.3084_.png
Saved: images_from_clusters_adducts/cluster_19_mz_450.0488_.png
Saved: images_from_clusters_adducts/cluster_24_mz_820.5273_.png
Saved: images_from_clusters_adducts/cluster_33_mz_367.0818_.png
Saved: images_from_clusters_adducts/cluster_52_mz_548.5356_.png
Saved: images_from_clusters_adducts/cluster_30_mz_685.0201_.png
Saved: images_from_clusters_adducts/cluster_18_mz_830.5131_.png
Saved: images_from_clusters_adducts/cluster_85_mz_897.0110_.png
Saved: images_from_clusters_adducts/cluster_6_mz_547.9938_.png
Saved: images_from_clusters_adducts/cluster_76_mz_465.1795_.png
Saved: images_from_clusters_adducts/cluster_14_mz_746.5800_.png
Saved: images_from_clusters_adducts/cluster_16_mz_277.0659_.png
Saved: images_from_clusters_adducts/cluster_12_mz_426.0626_.png
Saved: images_from_clusters_adducts/cluster_71_mz_443.0551_.png
Saved: images_from_clusters_adducts/cluster_83_mz_750.5461_.png
Saved: images_from_clusters_adducts/cluster_13_mz_199.9998_.png
Saved: images_from_clusters_adducts/cluster_26_mz_531.0173_.png
Saved: images_from_clusters_adducts/cluster_63_mz_551.5052_.png
Saved: images_from_clusters_adducts/cluster_20_mz_383.9606_.png
Saved: images_from_clusters_adducts/cluster_48_mz_603.0646_.png
Saved: images_from_clusters_adducts/cluster_18_mz_232.0653_.png
Saved: images_from_clusters_adducts/cluster_51_mz_210.9897_.png
Saved: images_from_clusters_adducts/cluster_69_mz_298.0454_.png
Saved: images_from_clusters_adducts/cluster_82_mz_559.9661_.png

Processing m/z features: 100%|██████████| 1000/1000 [19:55<00:00,  1.20s/it]
/opt/anaconda3/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning:

n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.

         mz  moran_I_tissue  geary_C_tissue  entropy_tissue  cv_tissue  \
0  136.0150        0.415658        0.547822        8.402684   0.965441
1  136.0608        0.262929        0.729385        8.702899   0.630088
2  137.0251        0.549667        0.406121        8.616154   0.964382
3  138.0287        0.508409        0.452354        8.596314   0.921969
4  139.0359        0.363029        0.612376        8.537266   0.820836

   skew_tissue  region_size  moran_I_background  geary_C_background  \
0     3.751760         6199            0.493544            0.501015
1     2.034254         7144            0.494965            0.504816
2     7.986627         7151            0.721676            0.275891
3     5.827630         7122            0.701255            0.295633
4     3.310123         6636            0.650540            0.345992

   entropy_background  ...  has_H_adduct  has_Na_adduct  has_K_adduct  \
0            9.055275  ...             1              1             0
1            8.685133  ...             0              0             0
2            8.950049  ...             1              1             0
3            8.989311  ...             1              0             0
4            9.013560  ...             0              0             0

   has_Mplus1_isotope  has_Mplus2_isotope  cluster      UMAP1     UMAP2  \
0                   1                   1       -1  -2.375989  1.969844
1                   0                   0        3  10.874235  5.166420
2                   1                   1       -1  -3.225951  1.220740
3                   1                   0       -1   2.204940  0.031811
4                   0                   0        3  11.452809  4.569888

       tSNE1      tSNE2
0 -21.737032  -2.620142
1  33.821030  10.016300
2 -26.214365   2.943655
3 -24.446104  11.643754
4  35.291515  16.119926

[5 rows x 22 columns]

(array([-1,  0,  1,  2,  3]), array([598,  63, 122,  36, 181]))